import { cancelReservation, reserveRooms } from "@/lib/availability";
import { currentUser } from "@/lib/auth-server";

const BOOKING_EMAIL="bookings@tripelor.com";
const BOOKING_BCC_EMAIL="johnshamil87@gmail.com";
function esc(v:unknown){return String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#039;");}
async function send(apiKey:string,payload:Record<string,unknown>){const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();return{response,result};}
function bookingRef(){const d=new Date();const date=`${d.getUTCFullYear()}${String(d.getUTCMonth()+1).padStart(2,"0")}${String(d.getUTCDate()).padStart(2,"0")}`;return`TRP-${date}-${Math.random().toString(36).slice(2,7).toUpperCase()}`;}
function db(){const url=process.env.SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;return{url,key};}
async function updateTripDetails(id:string,data:Record<string,unknown>){const{url,key}=db();if(!url||!key)return;await fetch(`${url}/rest/v1/reservations?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify(data)});}
async function validReferral(code:string,guestEmail:string){const{url,key}=db();if(!url||!key||!code)return null;const r=await fetch(`${url}/rest/v1/referral_codes?select=code,owner_email&code=eq.${encodeURIComponent(code)}&limit=1`,{headers:{apikey:key,Authorization:`Bearer ${key}`},cache:"no-store"});if(!r.ok)return null;const rows=await r.json();const row=rows?.[0];if(!row||String(row.owner_email).toLowerCase()===guestEmail.toLowerCase())return null;return row;}
async function createReferral(code:string,email:string,reservationId:string){const{url,key}=db();if(!url||!key)return;await fetch(`${url}/rest/v1/referrals`,{method:"POST",headers:{apikey:key,Authorization:`Bearer ${key}`,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({code,referred_email:email.toLowerCase(),reservation_id:reservationId,discount_usd:20,reward_points:200,status:"pending"})});}

export async function POST(request:Request){let reservationId:string|null=null;try{const user=await currentUser();if(!user)return Response.json({error:"Please log in to send a booking request."},{status:401});const apiKey=process.env.RESEND_API_KEY;if(!apiKey)return Response.json({error:"Email service is not configured yet."},{status:500});const b=await request.json();const{packageName,packagePrice,propertyName,fullName,email,phone,destination,checkIn,checkOut,checkInISO,checkOutISO,nights,adults,children,roomType,rooms,mealPlan,nightlyRate,estimatedTotal,speedboatSeats,speedboatTotal,specialRequests}=b;if(!fullName||!email||!checkIn||!checkOut||!propertyName||!roomType)return Response.json({error:"Booking details are incomplete."},{status:400});if(!checkInISO||!checkOutISO)return Response.json({error:"Unable to verify availability. Please select your dates again."},{status:400});
let referralCode="";try{const ref=request.headers.get("referer");if(ref)referralCode=(new URL(ref).searchParams.get("ref")||"").trim().toUpperCase()}catch{}const referral=referralCode?await validReferral(referralCode,email):null;const referralDiscount=referral?20:0;const grossTotal=Number(estimatedTotal||packagePrice||0);const finalTotal=grossTotal>0?Math.max(0,grossTotal-referralDiscount):grossTotal;
try{reservationId=await reserveRooms({propertyName,roomType,checkIn:checkInISO,checkOut:checkOutISO,rooms:Number(rooms||1),guestName:fullName,guestEmail:email,guestPhone:phone});}catch(e){const m=e instanceof Error?e.message:"";if(m.includes("ROOM_NOT_AVAILABLE"))return Response.json({error:"Sorry, this room is no longer available for the selected dates. Please choose another room or different dates."},{status:409});throw e;}
const reference=bookingRef(),title=packageName||`${propertyName} ${roomType}`;
if(reservationId){await updateTripDetails(reservationId,{booking_reference:reference,payment_status:"unpaid",package_name:packageName||null,estimated_total:finalTotal||null,speedboat_seats:Number(speedboatSeats||0),speedboat_total:Number(speedboatTotal||0),activities:packageName||null,notes:specialRequests||null,meal_plan:mealPlan||null,adults:Number(adults||1),children:Number(children||0),referral_code:referral?referralCode:null,referral_discount:referralDiscount});if(referral)await createReferral(referralCode,email,reservationId);}
const referralRow=referral?`<tr><td><b>Referral Discount</b></td><td style="color:#15803d"><b>- USD 20</b> · Code ${esc(referralCode)}</td></tr>`:"";
const rows=`${packageName?`<tr><td><b>Package</b></td><td>${esc(packageName)}</td></tr>`:""}${packagePrice?`<tr><td><b>Package Price</b></td><td>USD ${esc(packagePrice)}</td></tr>`:""}<tr><td><b>Stay / Hotel</b></td><td>${esc(propertyName)}</td></tr><tr><td><b>Room</b></td><td>${esc(roomType)}</td></tr><tr><td><b>Check-in</b></td><td>${esc(checkIn)}</td></tr><tr><td><b>Check-out</b></td><td>${esc(checkOut)}</td></tr><tr><td><b>Nights</b></td><td>${esc(nights)}</td></tr><tr><td><b>Adults</b></td><td>${esc(adults)}</td></tr><tr><td><b>Children</b></td><td>${esc(children)}</td></tr><tr><td><b>Meal Plan</b></td><td>${esc(mealPlan)}</td></tr>${nightlyRate?`<tr><td><b>Nightly Rate</b></td><td>USD ${esc(nightlyRate)}</td></tr>`:""}${speedboatSeats?`<tr><td><b>Speedboat</b></td><td>${esc(speedboatSeats)} seat(s) · USD ${esc(speedboatTotal)} · pay boat operator or Uhoo's Lavish Oasis</td></tr>`:""}${referralRow}${finalTotal?`<tr><td><b>Estimated Total</b></td><td><b>USD ${esc(finalTotal)}</b></td></tr>`:""}`;
const adminHtml=`<div style="font-family:Arial;max-width:680px;margin:auto;color:#111"><div style="background:#0a0a0a;color:#d4af37;padding:22px"><h1>New Tripelor Booking Request</h1><p style="color:#fff">Reference: <b>${reference}</b></p></div><div style="padding:24px;border:1px solid #ddd"><p><b>Reservation hold ID:</b> ${esc(reservationId)}</p><p><b>Guest:</b> ${esc(fullName)}<br><b>Email:</b> ${esc(email)}<br><b>Phone:</b> ${esc(phone)}<br><b>Destination:</b> ${esc(destination)}</p><table style="width:100%;border-spacing:0 10px"><tbody>${rows}</tbody></table><p><b>Special request:</b> ${esc(specialRequests||"None")}</p><p style="font-size:12px;color:#666">No payment has been taken. Review the request and send final confirmation before collecting payment.</p></div></div>`;
const{response:ar,result:aj}=await send(apiKey,{from:"Tripelor Bookings <bookings@tripelor.com>",to:[BOOKING_EMAIL],bcc:[BOOKING_BCC_EMAIL],reply_to:email,subject:`${reference} · ${esc(title)} · ${esc(fullName)}`,html:adminHtml});if(!ar.ok){if(reservationId)try{await cancelReservation(reservationId)}catch{}return Response.json({error:aj?.message||"Unable to send booking email."},{status:500});}
const customerHtml=`<div style="font-family:Arial;max-width:680px;margin:auto;color:#111"><div style="background:#0a0a0a;color:#d4af37;padding:22px"><h1>Tripelor Booking Request Received</h1><p style="color:#fff">Booking reference: <b>${reference}</b></p></div><div style="padding:24px;border:1px solid #ddd"><p>Dear ${esc(fullName)},</p><p>We received your booking request and placed the requested room on a pending hold while Tripelor reviews the details.</p>${referral?`<p style="background:#ecfdf5;border:1px solid #a7f3d0;padding:12px;border-radius:10px"><b>Your USD 20 referral discount has been applied.</b></p>`:""}<table style="width:100%;border-spacing:0 10px"><tbody>${rows}</tbody></table><p><b>No payment has been taken.</b> Your reservation becomes final only after Tripelor sends final confirmation and payment instructions.</p><p>Regards,<br><b>Tripelor</b><br>bookings@tripelor.com</p></div></div>`;try{await send(apiKey,{from:"Tripelor Bookings <bookings@tripelor.com>",to:[email],reply_to:BOOKING_EMAIL,subject:`${reference} · Tripelor booking request received`,html:customerHtml});}catch(e){console.error("Customer confirmation email error",e)}return Response.json({success:true,id:aj.id,reservationId,bookingReference:reference,referralApplied:Boolean(referral),referralDiscount,finalTotal});}catch(e){console.error("Booking email error",e);return Response.json({error:e instanceof Error?e.message:"Something went wrong while sending the booking request."},{status:500});}}
