import Link from "next/link";
import {BedDouble,MapPin,Star,Utensils} from "lucide-react";
import {properties} from "@/lib/properties";

export default function StaysPage(){return <main className="bg-[#080808] pb-24">
<section className="container py-12 md:py-16"><div className="mx-auto max-w-3xl text-center"><p className="text-sm uppercase tracking-[.32em] text-gold">Tripelor Properties</p><h1 className="mt-3 text-4xl font-bold md:text-6xl">Properties</h1><p className="mt-4 text-gray-400">All Tripelor guesthouses and hotels in one folder. Compare prices, open property details and book or request a stay.</p></div>
<div className="mt-10 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{properties.map(p=><article key={p.slug} className="overflow-hidden rounded-[1.8rem] border border-white/10 bg-[#111] shadow-2xl transition duration-300 hover:-translate-y-1 hover:border-gold/30">
<Link href={`/stays/${p.slug}`} className="block"><div className="relative h-64 overflow-hidden"><img src={p.images[0]} alt={p.name} className="h-full w-full object-cover transition duration-700 hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent"/><div className={`absolute left-4 top-4 rounded-full bg-black/65 px-3 py-1.5 text-xs font-semibold backdrop-blur ${p.bookingMode==="instant"?"text-emerald-300":"text-amber-300"}`}>{p.bookingMode==="instant"?"Live booking":"Request availability"}</div><div className="absolute right-4 top-4 rounded-full bg-black/65 px-3 py-1.5 text-xs text-white backdrop-blur">{p.images.length} photos</div><div className="absolute bottom-4 left-4 flex items-center gap-2 rounded-full bg-black/65 px-3 py-1.5 text-xs text-white backdrop-blur"><MapPin className="h-3.5 w-3.5 text-gold"/>{p.location}</div></div></Link>
<div className="flex gap-2 overflow-x-auto px-5 pt-4">{p.images.slice(0,5).map((img,i)=><Link key={img} href={`/stays/${p.slug}`} className="h-14 w-20 shrink-0 overflow-hidden rounded-lg border border-white/10"><img src={img} alt={`${p.name} photo ${i+1}`} className="h-full w-full object-cover"/></Link>)}</div>
<div className="p-5"><div className="flex items-start justify-between gap-3"><div><Link href={`/stays/${p.slug}`} className="text-xl font-bold transition hover:text-gold">{p.name}</Link><div className="mt-2 flex items-center gap-1 text-gold"><Star className="h-4 w-4 fill-current"/><Star className="h-4 w-4 fill-current"/><Star className="h-4 w-4 fill-current"/><Star className="h-4 w-4 fill-current"/><Star className="h-4 w-4 fill-current"/></div></div><span className="rounded-xl border border-white/10 px-3 py-2 text-xs text-gray-300"><BedDouble className="mr-1 inline h-3.5 w-3.5 text-gold"/>{p.roomsLabel}</span></div>
<p className="mt-3 text-sm leading-6 text-gray-400">{p.description}</p><div className="mt-5 grid grid-cols-2 gap-2">{p.rates.slice(0,4).map(r=><div key={r.label} className="rounded-xl border border-white/10 bg-white/[.025] p-3"><p className="text-xs text-gray-500">{r.label}</p><p className="mt-1 font-bold text-gold">USD {r.price}</p>{r.note&&<p className="mt-1 text-[11px] text-gray-600">{r.note}</p>}</div>)}</div>
<div className="mt-5 flex items-end justify-between gap-4 border-t border-white/10 pt-5"><div><p className="text-xs text-gray-500">From</p><p className="text-2xl font-black">USD {p.startingFrom}<span className="text-xs font-normal text-gray-500"> / night</span></p></div>{p.bookingMode==="instant"?<Link href={`/booking?property=${encodeURIComponent(p.name)}`} className="rounded-full bg-white px-5 py-3 text-sm font-bold text-black transition hover:bg-gold">Reserve</Link>:<Link href={`/stays/${p.slug}`} className="rounded-full bg-white px-5 py-3 text-sm font-bold text-black transition hover:bg-gold">Request Stay</Link>}</div>
<Link href={`/stays/${p.slug}`} className="mt-3 block text-center text-sm font-semibold text-gold">View property details & photos →</Link></div>
</article>)}</div></section>
<section className="container"><div className="rounded-3xl border border-gold/20 bg-gold/[.06] p-6 text-center md:p-8"><Utensils className="mx-auto h-6 w-6 text-gold"/><h2 className="mt-3 text-2xl font-bold">One simple Properties folder</h2><p className="mx-auto mt-2 max-w-2xl text-sm text-gray-400">New hotels can now be added to one central property catalog. Once the property name, photos, location, rates and booking method are added there, it automatically appears on this page.</p></div></section>
</main>}
