import Link from "next/link";
import {BedDouble,MapPin,Star,Utensils} from "lucide-react";

const properties=[
{name:"Uhoo's Lavish Oasis",slug:"uhoos-lavish-oasis",location:"V. Felidhoo, Maldives",image:"/uhoos/WhatsApp%20Image%202026-08-17%20at%2015.30.23.jpeg",rooms:"2 rooms",live:true,from:85,rates:[["BB","USD 85"],["HB","USD 95"],["FB","USD 115"]],bookHref:"/booking?property=Uhoo%27s%20Lavish%20Oasis&mealPlan=Bed%20%26%20Breakfast"},
{name:"Masfalhi View Inn",slug:"masfalhi-view-inn",location:"Maldives",image:"/images%20(3).jpeg",rooms:"6 rooms",live:true,from:97,rates:[["BB","USD 97"],["HB","USD 110"],["FB","USD 130"]],bookHref:"/booking?property=Masfalhi%20View%20Inn&mealPlan=Bed%20%26%20Breakfast"},
{name:"Rivethi Beach Hotel",slug:"rivethi-beach-hotel",location:"Hulhumalé, Maldives",image:"https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1400&q=88",rooms:"18 rooms",live:true,from:85,rates:[["RO","USD 85"],["BB","USD 95"],["Sea View BB","USD 130"],["Sea View FB","USD 195"]],bookHref:"/booking?property=Rivethi%20Beach%20Hotel&roomType=Deluxe%20Double&mealPlan=Bed%20%26%20Breakfast"}
];

export default function StaysPage(){return <main className="bg-[#080808] pb-24">
<section className="container py-12 md:py-16"><div className="mx-auto max-w-3xl text-center"><p className="text-sm uppercase tracking-[.32em] text-gold">Tripelor Properties</p><h1 className="mt-3 text-4xl font-bold md:text-6xl">Our stays</h1><p className="mt-4 text-gray-400">Choose your property, compare prices and book directly with live availability.</p></div>
<div className="mt-10 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{properties.map(p=><article key={p.slug} className="overflow-hidden rounded-[1.8rem] border border-white/10 bg-[#111] shadow-2xl transition duration-300 hover:-translate-y-1 hover:border-gold/30">
<Link href={`/stays/${p.slug}`} className="block"><div className="relative h-64 overflow-hidden"><img src={p.image} alt={p.name} className="h-full w-full object-cover transition duration-700 hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent"/><div className="absolute left-4 top-4 rounded-full bg-black/65 px-3 py-1.5 text-xs font-semibold text-emerald-300 backdrop-blur">Live availability</div><div className="absolute bottom-4 left-4 flex items-center gap-2 rounded-full bg-black/65 px-3 py-1.5 text-xs text-white backdrop-blur"><MapPin className="h-3.5 w-3.5 text-gold"/>{p.location}</div></div></Link>
<div className="p-5"><div className="flex items-start justify-between gap-3"><div><Link href={`/stays/${p.slug}`} className="text-xl font-bold transition hover:text-gold">{p.name}</Link><div className="mt-2 flex items-center gap-1 text-gold"><Star className="h-4 w-4 fill-current"/><Star className="h-4 w-4 fill-current"/><Star className="h-4 w-4 fill-current"/><Star className="h-4 w-4 fill-current"/><Star className="h-4 w-4 fill-current"/></div></div><span className="rounded-xl border border-white/10 px-3 py-2 text-xs text-gray-300"><BedDouble className="mr-1 inline h-3.5 w-3.5 text-gold"/>{p.rooms}</span></div>
<div className="mt-5 grid grid-cols-2 gap-2">{p.rates.map(([label,price])=><div key={label} className="rounded-xl border border-white/10 bg-white/[.025] p-3"><p className="text-xs text-gray-500">{label}</p><p className="mt-1 font-bold text-gold">{price}</p></div>)}</div>
<div className="mt-5 flex items-end justify-between gap-4 border-t border-white/10 pt-5"><div><p className="text-xs text-gray-500">From</p><p className="text-2xl font-black">USD {p.from}<span className="text-xs font-normal text-gray-500"> / night</span></p></div><Link href={p.bookHref} className="rounded-full bg-white px-5 py-3 text-sm font-bold text-black transition hover:bg-gold">Reserve</Link></div>
<Link href={`/stays/${p.slug}`} className="mt-3 block text-center text-sm font-semibold text-gold">View property details →</Link></div>
</article>)}</div></section>
<section className="container"><div className="rounded-3xl border border-gold/20 bg-gold/[.06] p-6 text-center md:p-8"><Utensils className="mx-auto h-6 w-6 text-gold"/><h2 className="mt-3 text-2xl font-bold">Choose the meal plan that suits your trip</h2><p className="mx-auto mt-2 max-w-2xl text-sm text-gray-400">Prices are shown clearly on each property card. Tap Reserve to continue to live availability and booking.</p></div></section>
</main>}
