"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, BedDouble, Utensils, Users, Mail, Hotel, MapPin, PackageCheck, Heart, SearchCheck } from "lucide-react";

const PROPERTY_RATES:Record<string,Record<string,number>>={"Uhoo's Lavish Oasis":{"Bed & Breakfast":85,"Half Board":95,"Full Board":115},"Masfalhi View Inn":{"Bed & Breakfast":80,"Half Board":90,"Full Board":100}};
const PACKAGE_HOTEL="Uhoo's Lavish Oasis";
function formatDate(date:string){if(!date)return"";return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${date}T00:00:00`));}
function addDays(date:string,days:number){if(!date)return"";const[y,m,d]=date.split("-").map(Number);const x=new Date(Date.UTC(y,m-1,d+days));return`${x.getUTCFullYear()}-${String(x.getUTCMonth()+1).padStart(2,"0")}-${String(x.getUTCDate()).padStart(2,"0")}`;}

export default function BookingPage(){
 const[propertyName,setPropertyName]=useState(PACKAGE_HOTEL),[packageName,setPackageName]=useState(""),[packagePrice,setPackagePrice]=useState<number|null>(null),[packageNights,setPackageNights]=useState(5),[adults,setAdults]=useState("2"),[children,setChildren]=useState("0"),[checkIn,setCheckIn]=useState(""),[checkOut,setCheckOut]=useState(""),[roomType,setRoomType]=useState("ROOM 101"),[mealPlan,setMealPlan]=useState("Bed & Breakfast"),[fullName,setFullName]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[specialRequests,setSpecialRequests]=useState(""),[sending,setSending]=useState(false),[status,setStatus]=useState(""),[availability,setAvailability]=useState<{available:boolean;rooms_left?:number}|null>(null),[checking,setChecking]=useState(false);

 useEffect(()=>{const p=new URLSearchParams(window.location.search);const property=p.get("property"),meal=p.get("mealPlan"),room=p.get("roomType"),cin=p.get("checkIn"),cout=p.get("checkOut");if(property)setPropertyName(property);if(meal)setMealPlan(meal);if(room)setRoomType(room);if(cin)setCheckIn(cin);if(cout)setCheckOut(cout);const n=Number(p.get("nights")||5);if(n===3||n===5)setPackageNights(n);const pkg=p.get("package")||"";if(pkg){const clean=pkg.replace(/\s*-\s*USD\s*\d+(?:\.\d+)?\s*$/i,"").trim();setPackageName(clean);setPropertyName(PACKAGE_HOTEL);const m=pkg.match(/USD\s*(\d+(?:\.\d+)?)/i);setPackagePrice(m?Number(m[1]):null);setAdults("2");setChildren("0")}},[]);
 useEffect(()=>{if(packageName&&checkIn)setCheckOut(addDays(checkIn,packageNights));},[packageName,checkIn,packageNights]);
 useEffect(()=>{setAvailability(null);},[propertyName,roomType,checkIn,checkOut]);
 const nights=useMemo(()=>{if(!checkIn||!checkOut)return 0;const diff=(new Date(`${checkOut}T00:00:00`).getTime()-new Date(`${checkIn}T00:00:00`).getTime())/86400000;return diff>0?Math.round(diff):0},[checkIn,checkOut]);
 const nightlyRate=PROPERTY_RATES[propertyName]?.[mealPlan]||0;const estimatedTotal=packageName&&packagePrice?packagePrice:nightlyRate*nights;const location=propertyName===PACKAGE_HOTEL?"V. Felidhoo, Maldives":"Maldives";
 function handleCheckIn(v:string){setCheckIn(v);setStatus("");if(packageName&&v)setCheckOut(addDays(v,packageNights));}
 async function checkAvailability(){setStatus("");if(!checkIn||!checkOut){setStatus("Please select your dates first.");return false;}setChecking(true);try{const r=await fetch("/api/availability",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({propertyName,roomType,checkIn,checkOut,rooms:1})});const x=await r.json();if(!r.ok)throw new Error(x?.error||"Unable to check availability.");setAvailability(x);if(!x.available)setStatus("Sorry, this room is not available for the selected dates. Please choose another room or different dates.");return Boolean(x.available);}catch(e){setStatus(e instanceof Error?e.message:"Unable to check availability.");return false;}finally{setChecking(false);}}
 function validate(){if(!checkIn||!checkOut){setStatus("Please select your check-in and check-out dates.");return false}if(nights<=0){setStatus("Check-out must be after check-in.");return false}if(packageName&&nights!==packageNights){setStatus(`This package is for exactly ${packageNights} nights.`);return false}if(!fullName.trim()){setStatus("Please enter your full name.");return false}if(!email.includes("@")){setStatus("Please enter a valid email address.");return false}if(!phone.trim()){setStatus("Please enter your phone number.");return false}return true}
 async function sendBookingEmail(){setStatus("");if(!validate())return;let ok=availability?.available;if(!ok)ok=await checkAvailability();if(!ok)return;setSending(true);try{const finalCheckOut=packageName?addDays(checkIn,packageNights):checkOut;const finalNights=packageName?packageNights:nights;const r=await fetch("/api/booking",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({packageName:packageName||null,packagePrice:packagePrice||null,propertyName:packageName?PACKAGE_HOTEL:propertyName,fullName:fullName.trim(),email:email.trim(),phone:phone.trim(),destination:location,checkIn:formatDate(checkIn),checkOut:formatDate(finalCheckOut),checkInISO:checkIn,checkOutISO:finalCheckOut,nights:finalNights,adults:packageName?"2":adults,children:packageName?"0":children,roomType,rooms:"1",mealPlan,nightlyRate:packageName?null:nightlyRate,estimatedTotal:estimatedTotal||null,specialRequests:packageName?`Couple package for 2 adults sharing ${roomType} at ${PACKAGE_HOTEL}.`:specialRequests.trim()})});const x=await r.json();if(!r.ok)throw new Error(x?.error||"Unable to send booking request.");const title=packageName||`${propertyName} · ${roomType}`;window.location.href=`/booking/confirmation?name=${encodeURIComponent(fullName.trim())}&title=${encodeURIComponent(title)}&dates=${encodeURIComponent(`${formatDate(checkIn)} – ${formatDate(finalCheckOut)}`)}`;}catch(e){setStatus(e instanceof Error?e.message:"Unable to send booking request.");setAvailability(null);}finally{setSending(false)}}
 return <section className="container py-12 md:py-16"><div className="mx-auto max-w-5xl"><p className="text-sm uppercase tracking-[.3em] text-gold">{packageName?"Book This Couple Package":"Book Your Stay"}</p><h1 className="mt-2 text-4xl font-bold md:text-5xl">{packageName?packageName:"Book your Maldives stay"}</h1><p className="mt-4 max-w-2xl text-gray-400">Choose your room and dates, check live availability, then send your request. Nothing is charged automatically.</p><div className="mt-10 grid gap-6 lg:grid-cols-[1fr_.38fr]"><form className="card grid gap-6 p-6 md:p-8" onSubmit={e=>e.preventDefault()}>
 {packageName&&<div className="rounded-2xl border border-gold/30 bg-gold/10 p-5"><div className="flex gap-3"><PackageCheck className="mt-1 h-6 w-6 text-gold"/><div><p className="text-xs uppercase tracking-[.2em] text-gold">Selected Couple Package</p><h2 className="mt-1 text-2xl font-bold">{packageName}</h2><p className="mt-2 flex items-center gap-2 text-gray-300"><Hotel className="h-4 w-4 text-gold"/>{PACKAGE_HOTEL} · V. Felidhoo</p><p className="mt-2 flex items-center gap-2 text-gray-300"><Heart className="h-4 w-4 text-gold"/>2 adults · 1 room · {packageNights} nights</p>{packagePrice&&<p className="mt-2 font-semibold text-gold">USD {packagePrice} total for the couple</p>}</div></div></div>}
 {!packageName&&<div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2 text-sm"><span className="flex items-center gap-2"><Hotel className="h-4 w-4 text-gold"/>Stay / Hotel</span><select value={propertyName} onChange={e=>setPropertyName(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3"><option>Uhoo&apos;s Lavish Oasis</option><option>Masfalhi View Inn</option></select></label><div className="grid gap-2 text-sm"><span className="flex items-center gap-2"><MapPin className="h-4 w-4 text-gold"/>Location</span><div className="rounded-xl border border-white/10 bg-black px-4 py-3">{location}</div></div></div>}
 <div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2 text-sm"><span className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-gold"/>Check-in</span><input type="date" value={checkIn} onChange={e=>handleCheckIn(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3"/></label><label className="grid gap-2 text-sm"><span className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-gold"/>Check-out</span><input type="date" value={checkOut} min={checkIn?addDays(checkIn,1):undefined} readOnly={!!packageName} onChange={e=>setCheckOut(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3 read-only:opacity-70"/></label></div>
 <div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2 text-sm"><span className="flex items-center gap-2"><BedDouble className="h-4 w-4 text-gold"/>Room</span><select value={roomType} onChange={e=>setRoomType(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3">{propertyName===PACKAGE_HOTEL?<><option>ROOM 101</option><option>ROOM 102</option></>:<option>Deluxe Room</option>}</select></label><label className="grid gap-2 text-sm"><span className="flex items-center gap-2"><Utensils className="h-4 w-4 text-gold"/>Meal plan</span><select value={mealPlan} disabled={!!packageName} onChange={e=>setMealPlan(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3 disabled:opacity-70"><option>Bed & Breakfast</option><option>Half Board</option><option>Full Board</option></select></label></div>
 {!packageName&&<div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2 text-sm"><span className="flex items-center gap-2"><Users className="h-4 w-4 text-gold"/>Adults</span><select value={adults} onChange={e=>setAdults(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3">{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label><label className="grid gap-2 text-sm"><span className="flex items-center gap-2"><Users className="h-4 w-4 text-gold"/>Children</span><select value={children} onChange={e=>setChildren(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3">{[0,1,2,3].map(n=><option key={n}>{n}</option>)}</select></label></div>}
 <button type="button" onClick={checkAvailability} disabled={checking||!checkIn||!checkOut} className="btn-outline gap-2 disabled:opacity-50"><SearchCheck className="h-4 w-4"/>{checking?"Checking...":"Check Live Availability"}</button>{availability&&<div className={`rounded-xl border p-4 text-sm ${availability.available?"border-green-500/30 bg-green-500/5 text-green-200":"border-red-500/30 bg-red-500/5 text-red-200"}`}>{availability.available?`${roomType} is available${typeof availability.rooms_left==="number"?` · ${availability.rooms_left} left`:""}.`:"This room is sold out for the selected dates."}</div>}
 <div className="grid gap-5 md:grid-cols-3"><input value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Full name" className="rounded-xl border border-white/10 bg-black px-4 py-3"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" type="email" className="rounded-xl border border-white/10 bg-black px-4 py-3"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone / WhatsApp" className="rounded-xl border border-white/10 bg-black px-4 py-3"/></div>{!packageName&&<textarea value={specialRequests} onChange={e=>setSpecialRequests(e.target.value)} rows={4} placeholder="Speedboat transfer, honeymoon setup, excursions or other requests" className="rounded-xl border border-white/10 bg-black px-4 py-3"/>}{status&&<div className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-3 text-sm">{status}</div>}
 </form><aside className="card h-fit border-gold/30 p-6 lg:sticky lg:top-24"><p className="text-xs uppercase tracking-[.22em] text-gold">Booking Summary</p><h2 className="mt-2 text-2xl font-bold">{packageName||propertyName}</h2><div className="mt-5 space-y-2 text-sm text-gray-300"><p>{roomType}</p>{checkIn&&checkOut&&<p>{formatDate(checkIn)} → {formatDate(checkOut)}</p>}<p>{packageName?`${packageNights} nights · 2 adults`:nights?`${nights} night${nights>1?"s":""}`:"Select dates"}</p><p>{mealPlan}</p></div>{estimatedTotal>0&&<div className="mt-6 border-t border-white/10 pt-5"><p className="text-xs text-gray-500">Estimated total</p><strong className="text-4xl text-gold">USD {estimatedTotal}</strong></div>}<button type="button" onClick={sendBookingEmail} disabled={sending} className="btn-gold mt-6 w-full gap-2 disabled:opacity-60"><Mail className="h-5 w-5"/>{sending?"Sending...":packageName?"Book This Package":"Send Booking Request"}</button><p className="mt-3 text-xs leading-5 text-gray-500">Subject to live availability and final Tripelor confirmation. No automatic charge is made.</p></aside></div></div>
 <div className="fixed inset-x-0 bottom-0 z-40 border-t border-white/10 bg-black/95 p-3 backdrop-blur lg:hidden"><button onClick={sendBookingEmail} disabled={sending} className="btn-gold w-full">{sending?"Sending...":packageName?"Book This Package":"Send Booking Request"}</button></div>
 </section>;
}
