"use client";

import { useEffect, useMemo, useState } from "react";
import { CalendarDays, BedDouble, Utensils, Users, Mail, Hotel, MapPin, PackageCheck, Heart } from "lucide-react";

const PROPERTY_RATES: Record<string, Record<string, number>> = {
  "Uhoo's Lavish Oasis": { "Bed & Breakfast": 85, "Half Board": 95, "Full Board": 115 },
  "Masfalhi View Inn": { "Bed & Breakfast": 80, "Half Board": 90, "Full Board": 100 },
};
const PROPERTY_ROOM_COUNTS: Record<string, number> = { "Uhoo's Lavish Oasis": 1, "Masfalhi View Inn": 6 };

function formatDate(date:string){if(!date)return "";return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${date}T00:00:00`));}
function addDays(date:string,days:number){if(!date)return "";const [year,month,day]=date.split('-').map(Number);const d=new Date(Date.UTC(year,month-1,day+days));return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`;}

export default function BookingPage(){
 const [propertyName,setPropertyName]=useState("Uhoo's Lavish Oasis"),[packageName,setPackageName]=useState(""),[packagePrice,setPackagePrice]=useState<number|null>(null),[packageNights,setPackageNights]=useState(5),[adults,setAdults]=useState("2"),[children,setChildren]=useState("0"),[checkIn,setCheckIn]=useState(""),[checkOut,setCheckOut]=useState(""),[roomType,setRoomType]=useState("ROOM 101"),[rooms,setRooms]=useState("1"),[mealPlan,setMealPlan]=useState("Bed & Breakfast"),[fullName,setFullName]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[specialRequests,setSpecialRequests]=useState(""),[sending,setSending]=useState(false),[status,setStatus]=useState("");
 useEffect(()=>{const p=new URLSearchParams(window.location.search);if(p.get("property"))setPropertyName(p.get("property")!);if(p.get("mealPlan"))setMealPlan(p.get("mealPlan")!);const n=Number(p.get("nights")||5);if(n===3||n===5)setPackageNights(n);const pkg=p.get("package")||"";if(pkg){const cleanName=pkg.replace(/\s*-\s*USD\s*\d+(?:\.\d+)?\s*$/i,"").trim();setPackageName(cleanName);const m=pkg.match(/USD\s*(\d+(?:\.\d+)?)/i);setPackagePrice(m?Number(m[1]):null);setAdults("2");setChildren("0");setRooms("1")}},[]);
 useEffect(()=>{if(packageName&&checkIn)setCheckOut(addDays(checkIn,packageNights));},[packageName,checkIn,packageNights]);
 useEffect(()=>{if(!packageName){const max=PROPERTY_ROOM_COUNTS[propertyName]??1;if(Number(rooms)>max)setRooms("1");if(propertyName==="Uhoo's Lavish Oasis"&&!['ROOM 101','ROOM 102'].includes(roomType))setRoomType('ROOM 101');if(propertyName==='Masfalhi View Inn'&&roomType!=='Deluxe Room')setRoomType('Deluxe Room')}},[propertyName,rooms,packageName,roomType]);
 const nights=useMemo(()=>{if(!checkIn||!checkOut)return 0;const d=Math.ceil((new Date(`${checkOut}T00:00:00`).getTime()-new Date(`${checkIn}T00:00:00`).getTime())/86400000);return d>0?d:0},[checkIn,checkOut]);
 const nightlyRate=PROPERTY_RATES[propertyName]?.[mealPlan],estimatedTotal=packageName&&packagePrice?packagePrice:(nightlyRate&&nights>0?nightlyRate*nights*Number(rooms):0),location=propertyName==="Uhoo's Lavish Oasis"?"V. Felidhoo, Maldives":"Maldives",packageCheckout=packageName&&checkIn?addDays(checkIn,packageNights):undefined,checkoutMin=checkIn?addDays(checkIn,1):undefined,maxRooms=PROPERTY_ROOM_COUNTS[propertyName]??1;
 function handleCheckIn(v:string){setCheckIn(v);setStatus('');if(packageName&&v)setCheckOut(addDays(v,packageNights))}
 function handleCheckOut(v:string){if(packageName&&checkIn){setCheckOut(addDays(checkIn,packageNights));return}setCheckOut(v);setStatus('')}
 function validate(){if(!checkIn){setStatus('Please select your check-in date.');return false}if(!packageName&&!checkOut){setStatus('Please select your check-out date.');return false}if(!packageName&&nights<=0){setStatus('Check-out date must be after the check-in date.');return false}if(!fullName.trim()){setStatus('Please enter your full name.');return false}if(!email.trim()||!email.includes('@')){setStatus('Please enter a valid email address.');return false}if(!phone.trim()){setStatus('Please enter your phone number.');return false}return true}
 async function sendBookingEmail(){setStatus('');if(!validate())return;setSending(true);try{const finalCheckOut=packageName?addDays(checkIn,packageNights):checkOut;const finalNights=packageName?packageNights:nights;if(packageName)setCheckOut(finalCheckOut);const r=await fetch('/api/booking',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({packageName:packageName||null,packagePrice:packagePrice||null,propertyName:packageName?null:propertyName,fullName:fullName.trim(),email:email.trim(),phone:phone.trim(),destination:packageName?'Maldives':location,checkIn:formatDate(checkIn),checkOut:formatDate(finalCheckOut),checkInISO:checkIn,checkOutISO:finalCheckOut,nights:finalNights,adults:packageName?'2':adults,children:packageName?'0':children,roomType:packageName?'Couple Room':roomType,rooms:packageName?'1':rooms,mealPlan,nightlyRate:packageName?null:(nightlyRate||null),estimatedTotal:estimatedTotal||null,specialRequests:packageName?'Couple package for 2 adults sharing 1 room.':specialRequests.trim()})});const x=await r.json();if(!r.ok)throw new Error(x?.error||'Unable to send booking request.');setStatus('Booking request sent successfully. A confirmation email has also been sent to you.')}catch(e){setStatus(e instanceof Error?e.message:'Unable to send booking request.')}finally{setSending(false)}}
 return <section className="container py-16"><div className="mx-auto max-w-5xl"><p className="text-sm uppercase tracking-[0.3em] text-gold">{packageName?'Book This Couple Package':'Book Your Stay'}</p><h1 className="mt-2 text-4xl font-bold md:text-5xl">{packageName?packageName:'Book your island guesthouse'}</h1><p className="mt-4 max-w-2xl text-gray-400">{packageName?`This ${packageNights}-night package is designed for 2 adults sharing 1 room.`:'Choose your guesthouse, dates and meal plan. Your booking request will be emailed directly to Tripelor.'}</p><form className="card mt-10 grid gap-6 p-6 md:p-8" onSubmit={e=>e.preventDefault()}>
 {packageName&&<div className="rounded-2xl border border-gold/30 bg-gold/10 p-5"><div className="flex items-start gap-3"><PackageCheck className="mt-1 h-6 w-6 text-gold"/><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-gold">Selected Couple Package</p><h2 className="mt-1 text-2xl font-bold">{packageName}</h2><p className="mt-2 flex items-center gap-2 text-gray-300"><Heart className="h-4 w-4 text-gold"/>2 adults · 1 room · {packageNights} nights</p>{packagePrice&&<p className="mt-2 text-gray-300"><strong className="text-gold">USD {packagePrice}</strong> total for the couple</p>}<p className="mt-1 text-sm text-gray-400">Meal plan: {mealPlan}</p></div></div></div>}
 {!packageName&&<><div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2"><span className="flex items-center gap-2 text-sm font-medium"><Hotel className="h-4 w-4 text-gold"/>Stay / Hotel</span><select value={propertyName} onChange={e=>setPropertyName(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3"><option>Uhoo&apos;s Lavish Oasis</option><option>Masfalhi View Inn</option></select></label><div className="grid gap-2"><span className="flex items-center gap-2 text-sm font-medium"><MapPin className="h-4 w-4 text-gold"/>Location</span><div className="rounded-xl border border-white/10 bg-black px-4 py-3">{location}</div></div></div><div className="rounded-xl border border-gold/30 bg-gold/10 px-4 py-3 text-sm text-gold">{propertyName} · BB ${PROPERTY_RATES[propertyName]['Bed & Breakfast']} · HB ${PROPERTY_RATES[propertyName]['Half Board']} · FB ${PROPERTY_RATES[propertyName]['Full Board']} per room/night</div></>}
 <div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2"><span className="flex items-center gap-2 text-sm font-medium"><CalendarDays className="h-4 w-4 text-gold"/>Check-in</span><input type="date" value={checkIn} onChange={e=>handleCheckIn(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3"/></label><label className="grid gap-2"><span className="flex items-center gap-2 text-sm font-medium"><CalendarDays className="h-4 w-4 text-gold"/>Check-out</span><input type="date" value={checkOut} min={checkoutMin} max={packageCheckout} readOnly={!!packageName} onChange={e=>handleCheckOut(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3 read-only:opacity-75"/></label></div>
 {packageName&&<p className="-mt-3 text-xs text-gray-500">Check-out is automatically fixed to exactly {packageNights} nights after check-in.</p>}
 {!packageName&&<><label className="grid gap-2"><span className="flex items-center gap-2 text-sm font-medium"><BedDouble className="h-4 w-4 text-gold"/>Number of rooms</span><select value={rooms} onChange={e=>setRooms(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3">{Array.from({length:maxRooms},(_,i)=>i+1).map(n=><option key={n} value={n}>{n} Room{n>1?'s':''}</option>)}</select></label>{nights>0&&<div className="rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-sm">Stay length: <span className="text-gold">{nights} night{nights===1?'':'s'}</span>{estimatedTotal>0&&<> · Estimated room total: <span className="font-semibold text-gold">USD {estimatedTotal}</span></>}</div>}<div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2"><span className="flex items-center gap-2 text-sm font-medium"><Users className="h-4 w-4 text-gold"/>Adults</span><select value={adults} onChange={e=>setAdults(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3">{[1,2,3,4,5,6,7,8].map(n=><option key={n}>{n}</option>)}</select></label><label className="grid gap-2"><span className="flex items-center gap-2 text-sm font-medium"><Users className="h-4 w-4 text-gold"/>Children</span><select value={children} onChange={e=>setChildren(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3">{[0,1,2,3,4,5,6].map(n=><option key={n}>{n}</option>)}</select></label></div><div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2"><span className="flex items-center gap-2 text-sm font-medium"><BedDouble className="h-4 w-4 text-gold"/>Room type</span><select value={roomType} onChange={e=>setRoomType(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3">{propertyName==="Uhoo's Lavish Oasis"?<><option>ROOM 101</option><option>ROOM 102</option></>:<option>Deluxe Room</option>}</select></label><label className="grid gap-2"><span className="flex items-center gap-2 text-sm font-medium"><Utensils className="h-4 w-4 text-gold"/>Meal plan</span><select value={mealPlan} onChange={e=>setMealPlan(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3"><option>Bed & Breakfast</option><option>Half Board</option><option>Full Board</option></select></label></div><p className="-mt-3 text-sm text-gray-400">Selected rate: <span className="font-semibold text-gold">USD {nightlyRate} per room/night</span></p></>}
 <div className="grid gap-5 md:grid-cols-3"><input value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Full name" className="rounded-xl border border-white/10 bg-black px-4 py-3"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" type="email" className="rounded-xl border border-white/10 bg-black px-4 py-3"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone number" className="rounded-xl border border-white/10 bg-black px-4 py-3"/></div>{!packageName&&<textarea value={specialRequests} onChange={e=>setSpecialRequests(e.target.value)} rows={4} placeholder="Special requests, speedboat transfer, honeymoon setup, excursions, etc." className="rounded-xl border border-white/10 bg-black px-4 py-3"/>}{status&&<div className="rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-sm text-gray-200">{status}</div>}<button type="button" onClick={sendBookingEmail} disabled={sending} className="btn-gold w-full gap-2 disabled:opacity-60 md:w-auto"><Mail className="h-5 w-5"/>{sending?'Sending...':packageName?'Book This Couple Package':'Send Booking Request'}</button><p className="text-xs text-gray-500">Booking requests are subject to availability and confirmation by Tripelor.</p></form></div></section>
}