const assert = require("node:assert/strict");
const { stripTypeScriptTypes } = require("node:module");
const fs = require("node:fs");
const source = stripTypeScriptTypes(fs.readFileSync(process.argv[2] || "lib/property-model.ts", "utf8")).replace(/^export /gm, "");
const { normalizePropertyArrival, publicProperty, validateProperty } = new Function(source + ";return {normalizePropertyArrival,publicProperty,validateProperty}")();
const empty=normalizePropertyArrival(undefined);
assert.equal(empty.meetingPoint,"");
assert.deepEqual(normalizePropertyArrival(null),empty);
assert.equal(normalizePropertyArrival({meetingPoint:"  Airport desk  "}).meetingPoint,"Airport desk");
assert.throws(()=>normalizePropertyArrival({meetingPoint:123}));
assert.throws(()=>normalizePropertyArrival({lateArrival:"x".repeat(2001)}));
assert.throws(()=>normalizePropertyArrival([]));
const input={name:"Example",slug:"example",status:"draft",island:"",description:"",photos:[],rooms:[],seasonalRates:[],inventoryRules:[],amenities:"",taxes:"",transfers:"USD 50 per person",cancellation:"",payment:"",partnerName:"Private manager",partnerEmail:"private@example.com",partnerPhone:"private",arrival:{...empty,contactName:"Guest team",meetingPoint:"Airport desk",privateSecret:"hidden"}};
const saved=validateProperty(input);
assert.equal(saved.data.arrival.meetingPoint,"Airport desk");
assert.equal(saved.data.arrival.privateSecret,undefined);
const output=publicProperty({...saved.data,id:"id",slug:"example",status:"draft",updated_at:""});
assert.equal(output.arrival.contactName,"Guest team");
assert.equal(output.transfers,"USD 50 per person");
assert.equal(output.partnerPhone,undefined);
assert.equal(JSON.stringify(output).includes("private@example.com"),false);
assert.deepEqual(validateProperty({...input,arrival:undefined}).data.arrival,empty);
console.log("PASS: legacy defaults, trimming, field validation, save/public roundtrip and private-contact exclusion.");
