import Link from "next/link";
import { Mail, MapPin, Ship, CircleHelp, ShieldCheck, Star, CheckCircle2, XCircle } from "lucide-react";

export const metadata = { title:"Travel Information, Policies & FAQs | Tripelor Maldives", description:"Tripelor Maldives travel information including transfers, FAQs, booking terms, cancellation policy, privacy and package inclusions." };

const faqs=[
 ["How do I request a booking?","Choose a stay or package, select your dates and submit the booking form. Tripelor will review availability and contact you by email. A booking request is not confirmed until you receive confirmation from Tripelor."],
 ["Are package prices final?","Displayed prices are the advertised package or room rates. Any optional transfers, extra activities, extra nights or special arrangements not listed as included will be quoted separately before confirmation."],
 ["What happens if weather affects an excursion?","Sea activities depend on weather, sea conditions and local safety guidance. When an activity cannot safely operate, Tripelor or the activity provider may reschedule it or offer an appropriate alternative where possible."],
 ["Can I request airport or speedboat transfers?","Yes. Tell us your international flight details or transfer request when booking. Transfer availability, schedule and price will be confirmed separately unless the selected package specifically states that transfers are included."],
];

export default function TravelInfo(){return <main className="container py-14 md:py-20"><p className="text-sm uppercase tracking-[.3em] text-gold">Plan with confidence</p><h1 className="mt-2 text-4xl font-bold md:text-6xl">Tripelor Travel Information</h1><p className="mt-5 max-w-3xl text-lg text-gray-400">Everything you should know before requesting your Maldives stay or island package.</p>
<section id="about" className="mt-14 grid gap-8 lg:grid-cols-2"><div className="card p-7"><ShieldCheck className="h-8 w-8 text-gold"/><h2 className="mt-4 text-3xl font-bold">About Tripelor</h2><p className="mt-4 leading-7 text-gray-400">Tripelor helps travelers discover local-island stays and memorable Maldives experiences. We bring accommodation, meal plans and selected island activities together in a simple booking-request experience, with personal support from enquiry through confirmation.</p></div><div id="contact" className="card p-7"><Mail className="h-8 w-8 text-gold"/><h2 className="mt-4 text-3xl font-bold">Contact</h2><p className="mt-4 text-gray-400">Questions about a stay, package, transfer or existing booking? Contact Tripelor and include your travel dates and number of guests.</p><div className="mt-5 space-y-3 text-gray-300"><p className="flex gap-2"><Mail className="h-5 w-5 text-gold"/>johnshamil87@gmail.com</p><p className="flex gap-2"><MapPin className="h-5 w-5 text-gold"/>Maldives</p></div><Link href="/booking" className="btn-gold mt-6">Send Booking Request</Link></div></section>
<section id="transfers" className="mt-14"><Ship className="h-8 w-8 text-gold"/><h2 className="mt-3 text-3xl font-bold">Transfer information</h2><p className="mt-4 max-w-4xl leading-7 text-gray-400">Local-island stays normally require onward transport from Malé / Velana International Airport. Depending on the island and travel date, this may be by scheduled speedboat, public ferry or a separately arranged private transfer. Schedules can change because of weather, operational requirements and public holidays. Please send your arrival and departure flight details before travel. Tripelor will confirm the suitable transfer option, timing and any additional cost before your booking is finalized.</p></section>
<section id="packages" className="mt-14"><h2 className="text-3xl font-bold">Package inclusions & exclusions</h2><div className="mt-6 grid gap-6 md:grid-cols-2"><div className="card p-7"><h3 className="text-xl font-semibold text-gold">Included</h3><div className="mt-4 space-y-3 text-gray-300">{["Accommodation for the number of nights stated","Meal plan specifically stated on the selected package","Activities specifically listed in the package","Tripelor booking support"].map(x=><p key={x} className="flex gap-2"><CheckCircle2 className="h-5 w-5 shrink-0 text-gold"/>{x}</p>)}</div></div><div className="card p-7"><h3 className="text-xl font-semibold">Not included unless stated</h3><div className="mt-4 space-y-3 text-gray-400">{["International flights","Airport / island transfers","Travel insurance","Personal expenses and optional activities","Extra nights, rooms or meals not included in the package"].map(x=><p key={x} className="flex gap-2"><XCircle className="h-5 w-5 shrink-0"/>{x}</p>)}</div></div></div><p className="mt-4 text-sm text-gray-500">The inclusions shown on the individual package page take priority if they differ from this general guide.</p></section>
<section id="faq" className="mt-14"><CircleHelp className="h-8 w-8 text-gold"/><h2 className="mt-3 text-3xl font-bold">Frequently Asked Questions</h2><div className="mt-6 grid gap-4">{faqs.map(([q,a])=><details key={q} className="card p-6"><summary className="cursor-pointer font-semibold">{q}</summary><p className="mt-4 leading-7 text-gray-400">{a}</p></details>)}</div></section>
<section id="reviews" className="mt-14"><Star className="h-8 w-8 text-gold"/><h2 className="mt-3 text-3xl font-bold">Guest reviews</h2><div className="card mt-6 p-7"><p className="text-gray-400">Verified guest testimonials will be displayed here as Tripelor collects permission to publish them. We do not publish invented reviews.</p></div></section>
<section id="terms" className="mt-14"><h2 className="text-3xl font-bold">Terms & Conditions</h2><div className="mt-5 space-y-4 leading-7 text-gray-400"><p>Submitting a booking form is a request only and does not create a confirmed reservation. Accommodation, activities, transfers and prices remain subject to availability until Tripelor sends confirmation.</p><p>Guests are responsible for providing accurate names, dates, contact details and travel information. Changes requested after confirmation may be subject to availability and additional charges.</p><p>Excursions and marine activities are subject to weather, sea conditions, operational availability and safety requirements. Itineraries may therefore be adjusted.</p><p>Guests should obtain appropriate travel insurance and comply with Maldives laws, property rules and activity-provider safety instructions.</p></div></section>
<section id="cancellation" className="mt-14"><h2 className="text-3xl font-bold">Cancellation Policy</h2><div className="card mt-5 p-7 text-gray-400"><p className="leading-7">Cancellation and amendment conditions can vary by guesthouse, package, activity and transfer provider. The applicable cancellation terms, payment schedule and any non-refundable amount will be provided to the customer before payment and booking confirmation. Where a third-party supplier applies stricter conditions, those supplier conditions may apply to the relevant part of the booking.</p></div></section>
<section id="privacy" className="mt-14"><h2 className="text-3xl font-bold">Privacy Policy</h2><div className="mt-5 space-y-4 leading-7 text-gray-400"><p>Tripelor collects information you provide through booking enquiries, such as your name, email address, phone number, travel dates and booking preferences, so we can process and respond to your request.</p><p>Booking information may be shared with relevant accommodation, transfer or activity providers when necessary to arrange the services you request. Tripelor does not sell your personal information.</p><p>Please avoid submitting sensitive information that is not required for your enquiry. If additional identification or travel information is needed for a confirmed service, Tripelor will advise you.</p></div></section>
<p className="mt-14 text-xs text-gray-500">Last updated: 17 August 2026. These website policies are general customer information and should be reviewed against your final commercial, payment and supplier arrangements before accepting paid bookings.</p></main>}
