"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {BellRing,Coffee,Home,LifeBuoy,Ship,Sparkles,Clock3,Waves,CheckCircle2} from "lucide-react";
const services=[
{key:"breakfast",label:"Breakfast",desc:"Request breakfast or breakfast timing assistance",icon:Coffee},
{key:"housekeeping",label:"Housekeeping",desc:"Request room cleaning, towels or linen help",icon:Home},
{key:"snorkeling",label:"Snorkeling Equipment",desc:"Request mask, snorkel or fins",icon:LifeBuoy},
{key:"excursion",label:"Excursion",desc:"Ask about manta, shark, turtle, dolphin or sandbank trips",icon:Waves},
{key:"late_checkout",label:"Late Checkout",desc:"Request a later checkout time, subject to availability",icon:Clock3},
{key:"speedboat",label:"Speedboat Assistance",desc:"Get help with departure or transfer arrangements",icon:Ship},
{key:"other",label:"Other Request",desc:"Anything else you need during your stay",icon:Sparkles}
];
export default function GuestPortal(){const[bookings,setBookings]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[type,setType]=useState("breakfast"),[details,setDetails]=useState(""),[when,setWhen]=useState(""),[sending,setSending]=useState(false),[status,setStatus]=useState("");
useEffect(()=>{(async()=>{const m=await fetch("/api/auth/me");const x=await m.json();if(!x.user){location.href="/login";return}const[b,r]=await Promise.all([fetch("/api/account/bookings"),fetch("/api/account/service-requests")]);const bx=await b.json(),rx=await r.json();if(b.ok)setBookings(bx.bookings||[]);if(r.ok)setRequests(rx.requests||[])})()},[]);
const stay=useMemo(()=>{const today=new Date();today.setHours(0,0,0,0);return bookings.find(b=>{if(String(b.status||"").toLowerCase()==="cancelled"||!b.check_in||!b.check_out)return false;const ci=new Date(`${b.check_in}T00:00:00`),co=new Date(`${b.check_out}T00:00:00`);return today>=ci&&today<co})||null},[bookings]);
async function send(){setStatus("");if(!stay){setStatus("Guest services are available during an active stay.");return}setSending(true);try{const r=await fetch("/api/account/service-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reservationId:stay.id,propertyName:stay.property_name,roomType:stay.room_type,requestType:type,details,requestedFor:when||null})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to send request.");setRequests(v=>[x.request,...v]);setDetails("");setWhen("");setStatus("Request sent to Tripelor. Our team will assist you shortly.")}catch(e){setStatus(e instanceof Error?e.message:"Unable to send request.")}finally{setSending(false)}}
return <main className="container py-12 pb-24 md:py-16"><div className="mx-auto max-w-5xl"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm uppercase tracking-[.3em] text-gold">During Your Stay</p><h1 className="mt-2 text-4xl font-bold md:text-5xl">Guest Portal 🛎️</h1><p className="mt-3 max-w-2xl text-gray-400">Request guest services directly from your phone while staying with Tripelor.</p></div><Link href="/account" className="btn-outline w-fit">Back to My Trip</Link></div>
{stay?<div className="mt-8 rounded-2xl border border-gold/25 bg-gold/10 p-5"><p className="text-xs uppercase tracking-[.22em] text-gold">Current Stay</p><h2 className="mt-1 text-2xl font-bold">{stay.property_name}</h2><p className="mt-1 text-gray-300">{stay.room_type} · {stay.check_in} → {stay.check_out}</p></div>:<div className="mt-8 rounded-2xl border border-white/10 bg-white/[.03] p-6"><p className="font-semibold">No active stay right now</p><p className="mt-2 text-sm text-gray-400">This portal activates automatically between your check-in and check-out dates.</p></div>}
<section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{services.map(s=>{const I=s.icon;return <button key={s.key} onClick={()=>setType(s.key)} disabled={!stay} className={`rounded-2xl border p-5 text-left transition ${type===s.key?"border-gold bg-gold/10":"border-white/10 bg-white/[.03] hover:border-gold/30"} disabled:opacity-50`}><I className="h-6 w-6 text-gold"/><h3 className="mt-3 font-semibold">{s.label}</h3><p className="mt-1 text-sm text-gray-400">{s.desc}</p></button>})}</section>
<section className="card mt-8 p-6 md:p-8"><div className="flex items-center gap-2"><BellRing className="h-5 w-5 text-gold"/><h2 className="text-xl font-bold">Send Request</h2></div><div className="mt-5 grid gap-4"><label className="grid gap-2 text-sm"><span>Preferred date/time (optional)</span><input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3"/></label><label className="grid gap-2 text-sm"><span>Details</span><textarea rows={4} value={details} onChange={e=>setDetails(e.target.value)} placeholder="Tell us what you need..." className="rounded-xl border border-white/10 bg-black px-4 py-3"/></label>{status&&<div className="rounded-xl border border-white/10 bg-white/[.04] p-4 text-sm">{status}</div>}<button onClick={send} disabled={!stay||sending} className="btn-gold w-full disabled:opacity-50 md:w-auto">{sending?"Sending...":"Send Guest Request"}</button></div></section>
<section className="mt-10"><h2 className="text-2xl font-bold">My Requests</h2>{requests.length===0?<div className="card mt-5 p-6 text-gray-400">No service requests yet.</div>:<div className="mt-5 grid gap-4 md:grid-cols-2">{requests.map(r=><article key={r.id} className="card p-5"><div className="flex items-center justify-between gap-3"><p className="font-semibold capitalize">{String(r.request_type).replaceAll("_"," ")}</p><span className={`rounded-full px-3 py-1 text-xs ${r.status==="completed"?"bg-green-500/10 text-green-300":"bg-gold/10 text-gold"}`}>{r.status}</span></div>{r.details&&<p className="mt-3 text-sm text-gray-300">{r.details}</p>}{r.requested_for&&<p className="mt-3 text-xs text-gray-500">Requested for: {new Date(r.requested_for).toLocaleString()}</p>}{r.status==="completed"&&<p className="mt-3 flex items-center gap-2 text-xs text-green-300"><CheckCircle2 className="h-4 w-4"/>Completed</p>}</article>)}</div>}</section>
</div></main>}
