"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { BedDouble, CalendarDays, CheckCircle2, Ship, Sparkles, Utensils } from "lucide-react";
import SaveTripButton from "@/components/save-trip-button";

const packageOptions=[
  {name:"Maldives Reef & Relax Escape",nights:3,price:500,meal:"Half Board"},{name:"Island Adventure",nights:3,price:750,meal:"Half Board"},{name:"Maldives Ocean Discovery Escape",nights:3,price:950,meal:"Full Board"},{name:"Beach BBQ Dinner Escape",nights:3,price:650,meal:"Half Board"},{name:"Honeymoon Island Escape",nights:3,price:900,meal:"Full Board"},{name:"Manta & Dolphin Adventure",nights:3,price:700,meal:"Half Board"},{name:"Sunset & Sandbank Escape",nights:3,price:550,meal:"Half Board"},
  {name:"Maldives Reef & Relax Escape",nights:5,price:750,meal:"Half Board"},{name:"5-Night Island Adventure",nights:5,price:950,meal:"Half Board"},{name:"Maldives Ocean Discovery Escape",nights:5,price:1150,meal:"Full Board"},{name:"Beach BBQ Dinner Escape",nights:5,price:990,meal:"Half Board"},{name:"Honeymoon Island Escape",nights:5,price:1350,meal:"Full Board"},{name:"Manta & Dolphin Adventure",nights:5,price:1050,meal:"Half Board"},{name:"Sunset & Sandbank Escape",nights:5,price:820,meal:"Half Board"}
];

export default function BuildYourTripPage(){
  const[nights,setNights]=useState(3),[room,setRoom]=useState("ROOM 101"),[selected,setSelected]=useState(0),[seats,setSeats]=useState(2);
  const options=packageOptions.filter(x=>x.nights===nights);const pkg=options[Math.min(selected,options.length-1)]||options[0];
  const speedboat=seats*50,total=(pkg?.price||0)+speedboat;
  const bookingHref=useMemo(()=>pkg?`/booking?package=${encodeURIComponent(pkg.name+" - USD "+pkg.price)}&mealPlan=${encodeURIComponent(pkg.meal)}&nights=${pkg.nights}&property=${encodeURIComponent("Uhoo's Lavish Oasis")}&roomType=${encodeURIComponent(room)}&speedboatSeats=${seats}&speedboatTotal=${speedboat}&planTotal=${total}`:"/booking",[pkg,room,seats,speedboat,total]);
  return <main className="container py-14 pb-28 md:py-20"><div className="mx-auto max-w-5xl"><p className="text-sm uppercase tracking-[.32em] text-gold">Tripelor Trip Builder</p><h1 className="mt-3 text-4xl font-bold md:text-6xl">Build your Maldives escape</h1><p className="mt-5 max-w-3xl text-gray-400">Choose your package, Uhoo&apos;s room and speedboat seats. Your complete plan follows you into the booking form.</p>
  <div className="mt-10 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><section className="card p-6 md:p-8"><div className="grid gap-7">
    <div><p className="mb-3 flex items-center gap-2 font-semibold"><CalendarDays className="h-5 w-5 text-gold"/>Trip length</p><div className="grid grid-cols-2 gap-3">{[3,5].map(n=><button key={n} type="button" onClick={()=>{setNights(n);setSelected(0)}} className={`rounded-2xl border px-5 py-4 text-left transition ${nights===n?"border-gold bg-gold/10 text-gold shadow-[0_0_30px_rgba(212,175,55,.08)]":"border-white/10 hover:border-gold/40"}`}><strong className="text-xl">{n} Nights</strong><span className="mt-1 block text-xs text-gray-400">Couple package · 2 adults</span></button>)}</div></div>
    <label className="grid gap-2"><span className="flex items-center gap-2 font-semibold"><Sparkles className="h-5 w-5 text-gold"/>Package</span><select value={selected} onChange={e=>setSelected(Number(e.target.value))} className="rounded-xl border border-white/10 bg-black px-4 py-3">{options.map((x,i)=><option key={`${x.name}-${x.nights}`} value={i}>{x.name} — USD {x.price}</option>)}</select></label>
    <div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2"><span className="flex items-center gap-2 font-semibold"><BedDouble className="h-5 w-5 text-gold"/>Room</span><select value={room} onChange={e=>setRoom(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3"><option>ROOM 101</option><option>ROOM 102</option></select></label><div className="grid gap-2"><span className="flex items-center gap-2 font-semibold"><Utensils className="h-5 w-5 text-gold"/>Meal plan</span><div className="rounded-xl border border-white/10 bg-black px-4 py-3 text-gray-300">{pkg?.meal}</div></div></div>
    <label className="grid gap-2"><span className="flex items-center gap-2 font-semibold"><Ship className="h-5 w-5 text-gold"/>Speedboat seats</span><select value={seats} onChange={e=>setSeats(Number(e.target.value))} className="rounded-xl border border-white/10 bg-black px-4 py-3">{Array.from({length:10},(_,i)=>i+1).map(n=><option key={n} value={n}>{n} seat{n>1?"s":""} — USD {n*50}</option>)}</select><span className="text-xs leading-5 text-gray-500">USD 50 per person. Speedboat requests must be made at least 24 hours before arrival. Payment can be made to the boat operator or Uhoo&apos;s Lavish Oasis.</span></label>
  </div></section>
  <aside className="card h-fit border-gold/30 p-6 md:p-8 lg:sticky lg:top-24"><p className="text-xs uppercase tracking-[.25em] text-gold">Your Tripelor plan</p><h2 className="mt-2 text-2xl font-bold">{pkg?.name}</h2><div className="mt-6 space-y-3 text-sm">{[`Uhoo's Lavish Oasis · ${room}`,`${nights} nights · 2 adults`,`${pkg?.meal} meal plan`,`${seats} speedboat seat${seats>1?"s":""}`].map(x=><p key={x} className="flex items-start gap-2 text-gray-300"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-gold"/>{x}</p>)}</div><div className="mt-7 border-t border-white/10 pt-6"><div className="flex justify-between text-sm text-gray-400"><span>Package</span><span>USD {pkg?.price}</span></div><div className="mt-2 flex justify-between text-sm text-gray-400"><span>Speedboat</span><span>USD {speedboat}</span></div><div className="mt-4 flex items-end justify-between"><span className="font-semibold">Estimated total</span><strong className="text-4xl text-gold">USD {total}</strong></div><p className="mt-3 text-xs leading-5 text-gray-500">Final availability and excursion conditions are confirmed before payment. No automatic charge is made online.</p><div className="mt-6 grid gap-3"><SaveTripButton itemType="package" itemKey={`${pkg?.name}-${nights}-${room}-${seats}`} title={pkg?.name||"Tripelor Package"} subtitle={`${nights} nights · ${room} · ${seats} speedboat seat${seats>1?"s":""} · USD ${total}`} href={bookingHref}/><Link href={bookingHref} className="btn-gold w-full">Continue to Booking</Link><Link href="/account/saved" className="text-center text-sm text-gold">View Saved Trips</Link></div></div></aside>
  </div></div></main>;
}
