import Link from "next/link";
import {CheckCircle2,Mail,MessageCircle,ShieldCheck,Hotel,Users,Utensils,Ship,PackageCheck,CreditCard,Phone,CalendarDays} from "lucide-react";
import VoucherActions from "@/components/voucher-actions";

type Reservation={booking_reference:string|null;property_name:string;room_type:string;check_in:string;check_out:string;guest_name:string;status:string;payment_status:string;package_name:string|null;estimated_total:number|null;speedboat_seats:number;speedboat_total:number;activities:string|null;notes:string|null;meal_plan:string|null;adults:number;children:number};
async function getReservation(ref:string):Promise<Reservation|null>{try{const url=process.env.SUPABASE_URL?.replace(/\/$/,"");const key=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!key||!ref||ref==="Pending")return null;const r=await fetch(`${url}/rest/v1/reservations?booking_reference=eq.${encodeURIComponent(ref)}&select=booking_reference,property_name,room_type,check_in,check_out,guest_name,status,payment_status,package_name,estimated_total,speedboat_seats,speedboat_total,activities,notes,meal_plan,adults,children&limit=1`,{headers:{apikey:key,Authorization:`Bearer ${key}`},cache:"no-store"});if(!r.ok)return null;const x=await r.json();return x?.[0]||null}catch{return null}}
const prettyDate=(v:string)=>{try{return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${v}T00:00:00`))}catch{return v}};

export default async function ConfirmationPage({searchParams}:{searchParams?:{name?:string;title?:string;dates?:string;ref?:string;total?:string}}){const ref=searchParams?.ref||"Pending";const booking=await getReservation(ref);const payment=booking?.payment_status?.toLowerCase()==="paid"?"Paid":"Payment pending";return <main className="container py-12 md:py-16">
<style>{`@media print{header,footer,.no-print{display:none!important}body{background:white!important;color:#111!important}.voucher{box-shadow:none!important;border:1px solid #ddd!important;background:white!important;color:#111!important}.voucher *{color:#111!important}.voucher .gold{color:#9a7600!important}}`}</style>
<div className="mx-auto max-w-4xl"><div className="no-print card overflow-hidden border-gold/30"><div className="bg-gradient-to-br from-gold/15 via-transparent to-transparent p-8 text-center md:p-10"><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-gold/10 ring-1 ring-gold/30"><CheckCircle2 className="h-9 w-9 text-gold"/></div><p className="mt-6 text-sm uppercase tracking-[.3em] text-gold">Request Received</p><h1 className="mt-3 text-4xl font-bold">Thank you{searchParams?.name?`, ${searchParams.name}`:""}.</h1><p className="mx-auto mt-4 max-w-xl leading-7 text-gray-300">Your booking request has been received. Your professional Tripelor voucher is ready below.</p></div></div>

<section className="voucher mt-8 overflow-hidden rounded-[2rem] border border-gold/30 bg-[#080808] shadow-2xl"><div className="flex flex-col gap-6 border-b border-white/10 bg-gradient-to-r from-gold/15 via-transparent to-transparent p-7 md:flex-row md:items-center md:justify-between md:p-9"><div><p className="gold text-sm font-semibold uppercase tracking-[.35em] text-gold">Tripelor</p><h2 className="mt-2 text-3xl font-bold md:text-4xl">Booking Voucher</h2><p className="mt-2 text-sm text-gray-400">Maldives Travel & Stay Confirmation</p></div><div className="rounded-2xl border border-gold/30 bg-black/30 px-5 py-4"><p className="text-xs uppercase tracking-[.2em] text-gray-500">Booking Reference</p><p className="gold mt-1 text-2xl font-bold text-gold">{ref}</p></div></div>
<div className="p-7 md:p-9"><div className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-white/10 p-5"><p className="flex items-center gap-2 text-xs uppercase tracking-[.18em] text-gray-500"><Hotel className="h-4 w-4 text-gold"/>Hotel</p><p className="mt-2 text-xl font-semibold">{booking?.property_name||searchParams?.title||"Tripelor Stay"}</p><p className="mt-1 text-gray-400">{booking?.room_type||"Room details pending"}</p></div><div className="rounded-2xl border border-white/10 p-5"><p className="flex items-center gap-2 text-xs uppercase tracking-[.18em] text-gray-500"><Users className="h-4 w-4 text-gold"/>Guest</p><p className="mt-2 text-xl font-semibold">{booking?.guest_name||searchParams?.name||"Guest"}</p><p className="mt-1 text-gray-400">{booking?`${booking.adults} adult${booking.adults===1?"":"s"}${booking.children?` · ${booking.children} child${booking.children===1?"":"ren"}`:""}`:"Guest details on confirmation"}</p></div></div>
<div className="mt-4 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-white/10 p-5"><CalendarDays className="h-5 w-5 text-gold"/><p className="mt-3 text-xs uppercase tracking-[.16em] text-gray-500">Check-in</p><p className="mt-1 font-semibold">{booking?prettyDate(booking.check_in):searchParams?.dates||"Pending"}</p></div><div className="rounded-2xl border border-white/10 p-5"><CalendarDays className="h-5 w-5 text-gold"/><p className="mt-3 text-xs uppercase tracking-[.16em] text-gray-500">Check-out</p><p className="mt-1 font-semibold">{booking?prettyDate(booking.check_out):"See booking dates"}</p></div><div className="rounded-2xl border border-white/10 p-5"><Utensils className="h-5 w-5 text-gold"/><p className="mt-3 text-xs uppercase tracking-[.16em] text-gray-500">Meal Plan</p><p className="mt-1 font-semibold">{booking?.meal_plan||"As booked"}</p></div></div>
<div className="mt-4 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-white/10 p-5"><PackageCheck className="h-5 w-5 text-gold"/><p className="mt-3 text-xs uppercase tracking-[.16em] text-gray-500">Package / Activities</p><p className="mt-1 font-semibold">{booking?.activities||booking?.package_name||"No package activities added"}</p></div><div className="rounded-2xl border border-white/10 p-5"><Ship className="h-5 w-5 text-gold"/><p className="mt-3 text-xs uppercase tracking-[.16em] text-gray-500">Speedboat Transfer</p><p className="mt-1 font-semibold">{booking&&booking.speedboat_seats>0?`${booking.speedboat_seats} seat${booking.speedboat_seats===1?"":"s"} requested`:"Not added"}</p>{booking&&booking.speedboat_total>0&&<p className="mt-1 text-sm text-gray-400">USD {Number(booking.speedboat_total).toFixed(2)}</p>}</div><div className="rounded-2xl border border-white/10 p-5"><CreditCard className="h-5 w-5 text-gold"/><p className="mt-3 text-xs uppercase tracking-[.16em] text-gray-500">Payment</p><p className={`mt-1 font-semibold ${payment==="Paid"?"text-emerald-300":"text-amber-300"}`}>{payment}</p><p className="gold mt-1 text-lg font-bold text-gold">USD {booking?.estimated_total!=null?Number(booking.estimated_total).toFixed(2):(searchParams?.total||"0")}</p></div></div>
{booking?.notes&&<div className="mt-4 rounded-2xl border border-white/10 p-5"><p className="text-xs uppercase tracking-[.16em] text-gray-500">Special Requests / Notes</p><p className="mt-2 text-sm leading-6 text-gray-300">{booking.notes}</p></div>}
<div className="mt-6 grid gap-4 md:grid-cols-2"><div className="rounded-2xl border border-gold/25 bg-gold/5 p-5"><ShieldCheck className="h-5 w-5 text-gold"/><p className="mt-2 font-semibold">Booking status</p><p className="mt-1 text-sm text-gray-400">{booking?.status||"Pending"}. This voucher records your Tripelor booking request. Final confirmation and payment instructions are issued by Tripelor.</p></div><div className="rounded-2xl border border-white/10 p-5"><Phone className="h-5 w-5 text-gold"/><p className="mt-2 font-semibold">Emergency / Travel Support</p><p className="mt-1 text-sm text-gray-400">WhatsApp: +960 942 9403</p><p className="text-sm text-gray-400">Email: bookings@tripelor.com</p></div></div>
<div className="mt-7 border-t border-white/10 pt-5 text-center text-xs text-gray-500">Tripelor · Maldives · Please keep this voucher available on your phone during your journey.</div></div></section>
<VoucherActions/>
<div className="no-print mt-8 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 p-4 text-center"><Mail className="mx-auto h-5 w-5 text-gold"/><p className="mt-2 text-sm">A booking summary is also sent by email.</p></div><div className="rounded-2xl border border-white/10 p-4 text-center"><ShieldCheck className="mx-auto h-5 w-5 text-gold"/><p className="mt-2 text-sm">No automatic charge is taken.</p></div><a href="https://wa.me/9609429403" className="rounded-2xl border border-white/10 p-4 text-center"><MessageCircle className="mx-auto h-5 w-5 text-gold"/><p className="mt-2 text-sm">Contact Tripelor on WhatsApp.</p></a></div><div className="no-print mt-8 flex flex-wrap justify-center gap-3"><Link href="/" className="btn-outline">Back Home</Link><Link href="/account" className="btn-gold">My Trip</Link></div></div></main>}
