"use client";
import Link from "next/link";
import {useState} from "react";
import {KeyRound,Mail} from "lucide-react";

export default function ForgotPasswordPage(){
 const[email,setEmail]=useState("");const[status,setStatus]=useState("");const[busy,setBusy]=useState(false);const[done,setDone]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setStatus("");try{const r=await fetch("/api/auth/forgot-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to send reset email.");setDone(true);setStatus(x.message);}catch(e){setStatus(e instanceof Error?e.message:"Unable to send reset email.");}finally{setBusy(false)}}
 return <main className="relative min-h-screen overflow-hidden"><img src="https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=2200&q=90" alt="Maldives" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-black/75"/><div className="container relative flex min-h-screen items-center justify-center py-12"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-black/85 p-7 shadow-2xl backdrop-blur-xl md:p-9"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full border border-gold/30 bg-gold/10"><KeyRound className="h-5 w-5 text-gold"/></div><p className="mt-5 text-center text-sm uppercase tracking-[.35em] text-gold">Tripelor</p><h1 className="mt-3 text-center text-3xl font-bold">Forgot your password?</h1><p className="mt-3 text-center text-sm leading-6 text-gray-400">Enter the email used for your Tripelor account and we’ll send you a secure password reset link.</p><form onSubmit={submit} className="mt-8 grid gap-5"><label className="grid gap-2 text-sm"><span className="flex items-center gap-2"><Mail className="h-4 w-4 text-gold"/>Email address</span><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email" className="rounded-xl border border-white/10 bg-black/70 px-4 py-3"/></label>{status&&<p className={`rounded-xl border p-3 text-sm ${done?"border-green-500/30 bg-green-500/10 text-green-200":"border-white/10 bg-white/[.05]"}`}>{status}</p>}<button disabled={busy||done} className="btn-gold disabled:opacity-60">{busy?"Sending...":done?"Reset link sent":"Send Reset Link"}</button><Link href="/login" className="text-center text-sm text-gray-400 transition hover:text-gold">← Back to login</Link></form></div></div></main>}
