"use client";
import Link from "next/link";
import {useState} from "react";
import {KeyRound,Mail,CheckCircle2} from "lucide-react";

export default function ForgotPasswordPage(){
 const[email,setEmail]=useState("");const[status,setStatus]=useState("");const[busy,setBusy]=useState(false);const[done,setDone]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setStatus("");try{const r=await fetch("/api/auth/forgot-password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to send reset email.");setDone(true);setStatus(x.message);}catch(e){setStatus(e instanceof Error?e.message:"Unable to send reset email.");}finally{setBusy(false)}}
 return <main className="relative min-h-screen overflow-hidden"><img src="https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=2200&q=90" alt="Maldives" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-black/75"/><div className="container relative flex min-h-screen items-center justify-center py-12"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-black/85 p-7 shadow-2xl backdrop-blur-xl md:p-9"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full border border-gold/30 bg-gold/10"><KeyRound className="h-5 w-5 text-gold"/></div><p className="mt-5 text-center text-sm uppercase tracking-[.35em] text-gold">Tripelor</p><h1 className="mt-3 text-center text-3xl font-bold">Reset your password</h1>{!done?<><p className="mt-3 text-center text-sm leading-6 text-gray-400">Enter the email used for your Tripelor account. We’ll email you a secure link to create a new password.</p><form onSubmit={submit} className="mt-8 grid gap-5"><label className="grid gap-2 text-sm"><span className="flex items-center gap-2"><Mail className="h-4 w-4 text-gold"/>Email address</span><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" autoComplete="email" className="rounded-xl border border-white/10 bg-black/70 px-4 py-3"/></label>{status&&<p className="rounded-xl border border-white/10 bg-white/[.05] p-3 text-sm">{status}</p>}<button disabled={busy} className="btn-gold disabled:opacity-60">{busy?"Sending...":"Send Reset Link"}</button><Link href="/login" className="text-center text-sm text-gray-400 transition hover:text-gold">← Back to login</Link></form></>:<div className="mt-7 grid gap-5"><div className="rounded-2xl border border-green-500/30 bg-green-500/10 p-5"><CheckCircle2 className="h-6 w-6 text-green-300"/><h2 className="mt-3 text-xl font-bold text-white">Next: Create New Password</h2><p className="mt-2 text-sm leading-6 text-green-100/80">We sent the reset link to <strong>{email}</strong>. Open that email and tap the password reset link. Tripelor will then open the <strong>Create a New Password</strong> screen automatically.</p></div><div className="rounded-2xl border border-gold/20 bg-gold/[.06] p-4 text-sm text-gray-300"><strong className="text-gold">Can’t see the email?</strong><p className="mt-1 text-gray-400">Check Spam or Junk, then wait a minute and request another link if needed.</p></div><button type="button" onClick={()=>{setDone(false);setStatus("")}} className="btn-outline">Send Another Reset Link</button><Link href="/login" className="text-center text-sm text-gray-400 transition hover:text-gold">← Back to login</Link></div>}</div></div></main>}
