"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { CalendarDays, Gift, LogOut, ShieldCheck, Sparkles, UserRound } from "lucide-react";
type User={email:string;fullName:string;isAdmin?:boolean};
export default function AccountPage(){
 const[user,setUser]=useState<User|null>(null);const[bookings,setBookings]=useState<any[]>([]);const[loyalty,setLoyalty]=useState<any>(null);const[loading,setLoading]=useState(true);const[status,setStatus]=useState("");
 useEffect(()=>{(async()=>{try{const m=await fetch("/api/auth/me",{cache:"no-store"});const mx=await m.json();if(!mx.user){window.location.href="/login";return;}setUser(mx.user);const[b,l]=await Promise.all([fetch("/api/account/bookings",{cache:"no-store"}),fetch("/api/account/loyalty",{cache:"no-store"})]);const bx=await b.json();const lx=await l.json();if(b.ok)setBookings(bx.bookings||[]);else setStatus(bx.error||"Unable to load bookings.");if(l.ok)setLoyalty(lx);}finally{setLoading(false)}})()},[]);
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});window.location.href="/";}
 if(loading)return <main className="container py-20"><p className="text-gray-400">Loading your Tripelor account...</p></main>;if(!user)return null;
 const points=Number(loyalty?.account?.points_balance||0);const target=Number(loyalty?.pointsForFreeNight||1000);const progress=Math.min(100,(points%target)/target*100);const freeNights=Math.floor(points/target);
 return <main className="container py-14 md:py-20"><div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="text-sm uppercase tracking-[.3em] text-gold">My Tripelor</p><h1 className="mt-2 text-4xl font-bold md:text-5xl">Welcome{user.fullName?`, ${user.fullName}`:""}</h1><p className="mt-2 text-gray-400">{user.email}</p></div><div className="flex flex-wrap gap-3">{user.isAdmin&&<Link href="/admin" className="btn-outline gap-2"><ShieldCheck className="h-4 w-4"/>Admin Dashboard</Link>}<button onClick={logout} className="btn-outline gap-2"><LogOut className="h-4 w-4"/>Log Out</button></div></div>
 <section className="mt-10 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><div className="card border-gold/30 p-6 md:p-8"><div className="flex items-center gap-3"><Sparkles className="h-7 w-7 text-gold"/><div><p className="text-xs uppercase tracking-[.25em] text-gold">Tripelor Rewards</p><h2 className="text-2xl font-bold">{points} points</h2></div></div><p className="mt-4 text-gray-300">Earn <strong className="text-gold">100 points for every completed paid room-night</strong>. Every <strong className="text-gold">1,000 points</strong> unlocks one free night.</p><div className="mt-6 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gold transition-all" style={{width:`${freeNights>0?100:progress}%`}}/></div><div className="mt-3 flex justify-between text-xs text-gray-400"><span>{freeNights>0?`${freeNights} free night${freeNights>1?"s":""} available`:`${points%target} / ${target} points`}</span><span>{freeNights>0?"Reward ready":`${target-(points%target)} points to go`}</span></div></div><div className="card p-6 md:p-8"><Gift className="h-7 w-7 text-gold"/><h3 className="mt-3 text-xl font-bold">Free Night Reward</h3><p className="mt-2 text-gray-400">Free nights are subject to room availability and Tripelor confirmation. Contact us when you are ready to redeem.</p>{freeNights>0?<a href="https://wa.me/9609429403?text=Hello%20Tripelor%2C%20I%20would%20like%20to%20redeem%20my%20free%20night%20reward." className="btn-gold mt-5">Redeem Free Night</a>:<Link href="/booking" className="btn-outline mt-5">Earn More Points</Link>}</div></section>
 <section className="mt-10"><div className="flex items-center gap-3"><CalendarDays className="h-6 w-6 text-gold"/><h2 className="text-2xl font-bold">My Bookings</h2></div>{status&&<p className="mt-5 rounded-xl border border-red-500/20 bg-red-500/5 p-4 text-sm">{status}</p>}{bookings.length===0?<div className="card mt-6 p-8 text-center"><UserRound className="mx-auto h-8 w-8 text-gold"/><h3 className="mt-3 text-xl font-semibold">No bookings yet</h3><p className="mt-2 text-gray-400">Bookings made with this email address will appear here.</p><Link href="/build-your-trip" className="btn-gold mt-5">Plan a Maldives Trip</Link></div>:<div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{bookings.map((b,i)=><article key={b.id||i} className="card p-6"><div className="flex items-center justify-between gap-3"><p className="text-xs uppercase tracking-[.2em] text-gold">{b.status||"Booking"}</p>{b.created_at&&<span className="text-xs text-gray-500">{new Date(b.created_at).toLocaleDateString("en-GB")}</span>}</div><h3 className="mt-3 text-xl font-bold">{b.property_name||b.propertyName||"Tripelor Stay"}</h3><p className="mt-2 text-gray-300">{b.room_type||b.roomType||"Room"}</p><div className="mt-4 space-y-1 text-sm text-gray-400"><p>{b.check_in||b.checkIn||""} {b.check_out||b.checkOut?`→ ${b.check_out||b.checkOut}`:""}</p>{b.guest_name&&<p>Guest: {b.guest_name}</p>}</div>{String(b.status||"").toLowerCase()==="completed"&&<p className="mt-4 rounded-xl bg-gold/10 px-3 py-2 text-xs text-gold">Reward points earned for this stay.</p>}</article>)}</div>}</section></main>}
