import Image from "next/image";
import Link from "next/link";
import { Globe2, ShieldCheck, Sparkles, MapPin, Utensils } from "lucide-react";

const stays = [
  { name: "Uhoo's Lavish Oasis", slug: "uhoos-lavish-oasis", location: "V. Felidhoo, Maldives", image: "/uhoos/WhatsApp%20Image%202026-08-17%20at%2015.30.23.jpeg", description: "Comfortable rooms, warm island hospitality and flexible meal plans for a relaxed Felidhoo getaway.", rates: { "Bed & Breakfast": 85, "Half Board": 95, "Full Board": 115 } },
  { name: "Masfalhi View Inn", slug: "masfalhi-view-inn", location: "Maldives", image: "/images%20(3).jpeg", description: "A comfortable local island guesthouse stay with flexible meal plans and friendly Maldivian hospitality.", rates: { "Bed & Breakfast": 80, "Half Board": 90, "Full Board": 100 } },
];

export default function Home() { return <>
<section className="relative min-h-[78vh] overflow-hidden"><Image src="https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2200&auto=format&fit=crop" alt="Luxury tropical destination" fill priority className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-black via-black/70 to-black/20"/><div className="container relative flex min-h-[78vh] items-center"><div className="max-w-3xl py-24"><p className="mb-4 text-sm font-semibold uppercase tracking-[0.35em] text-gold">Discover. Escape. Remember.</p><h1 className="text-5xl font-bold leading-tight md:text-7xl">Travel beautifully with <span className="text-gold">Tripelor</span></h1><p className="mt-6 max-w-2xl text-lg text-gray-200">Relaxing island stays and memorable experiences, thoughtfully arranged for you.</p><Link href="/booking" className="btn-gold mt-8">Book Your Stay</Link></div></div></section>
<section className="border-y border-white/10 bg-white/[0.02]"><div className="container py-20"><div className="mb-10"><p className="text-sm uppercase tracking-[0.3em] text-gold">Our Stays</p><h2 className="mt-2 text-4xl font-bold">Choose your island guesthouse</h2></div><div className="grid gap-8 lg:grid-cols-2">{stays.map(stay=><article key={stay.name} className="card overflow-hidden"><div className="h-80 overflow-hidden"><img src={stay.image} alt={stay.name} className="h-full w-full object-cover"/></div><div className="p-7"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-gold">Island Guesthouse</p><h3 className="mt-2 text-3xl font-bold">{stay.name}</h3><p className="mt-2 flex items-center gap-2 text-gray-400"><MapPin className="h-4 w-4 text-gold"/>{stay.location}</p><p className="mt-4 text-gray-400">{stay.description}</p><div className="mt-6 space-y-3">{Object.entries(stay.rates).map(([plan,price])=><div key={plan} className="flex items-center justify-between rounded-xl border border-white/10 px-4 py-3"><span className="flex items-center gap-2"><Utensils className="h-4 w-4 text-gold"/>{plan}</span><strong className="text-gold">USD {price}</strong></div>)}</div><p className="mt-3 text-xs text-gray-500">Rates are per room, per night.</p><div className="mt-7 flex flex-wrap gap-3"><Link href={`/stays/${stay.slug}`} className="btn-outline">View Stay</Link><Link href={`/booking?property=${encodeURIComponent(stay.name)}&mealPlan=Bed%20%26%20Breakfast`} className="btn-gold">Book Now</Link></div></div></article>)}</div></div></section>
<section className="border-b border-white/10 bg-white/[0.02]"><div className="container grid gap-8 py-16 md:grid-cols-3"><div className="card p-6"><Sparkles className="h-8 w-8 text-gold"/><h3 className="mt-4 text-xl font-semibold">Curated for you</h3><p className="mt-2 text-gray-400">Comfortable island stays tailored to your dates and meal preference.</p></div><div className="card border-gold/30 p-6"><Globe2 className="h-8 w-8 text-gold"/><p className="mt-4 text-xs font-semibold uppercase tracking-[0.2em] text-gold">5-Night Package</p><h3 className="mt-2 text-2xl font-semibold">Island Adventures</h3><p className="mt-2 text-gray-400">Snorkeling, sandbank escape, dolphins, fishing and island hopping — five nights made for memories.</p><div className="mt-5 flex items-end justify-between gap-4"><div><span className="text-3xl font-bold text-gold">USD 540</span><p className="text-xs text-gray-500">Adventure package</p></div><Link href="/island-adventures" className="btn-gold">Explore Package</Link></div></div><div className="card p-6"><ShieldCheck className="h-8 w-8 text-gold"/><h3 className="mt-4 text-xl font-semibold">Trusted support</h3><p className="mt-2 text-gray-400">Personal guidance before, during, and after your stay.</p></div></div></section>
<section className="container py-20 text-center"><p className="text-sm uppercase tracking-[0.3em] text-gold">Your island escape</p><h2 className="mx-auto mt-3 max-w-3xl text-4xl font-bold md:text-5xl">Choose your stay and start planning your Maldives escape.</h2><Link href="/booking" className="btn-gold mt-8">Book Your Stay</Link></section>
</> }
