import Image from "next/image";
import Link from "next/link";
import { Waves, Sun, Fish, Ship, Map, CheckCircle2, Moon, Sparkles, Utensils } from "lucide-react";

const adventures = [
  { icon: Waves, title: "Snorkeling Adventure", text: "Slip into crystal-clear Maldivian waters and discover colorful reef fish, corals and the beautiful underwater world around the islands." },
  { icon: Sun, title: "Sandbank Escape", text: "Spend time on a tiny stretch of white sand surrounded by turquoise ocean — perfect for swimming, relaxing and unforgettable holiday photos." },
  { icon: Fish, title: "Dolphin Cruise", text: "Cruise across the open sea while looking for playful dolphins. Enjoy the ocean breeze, beautiful views and one of the Maldives' most exciting wildlife experiences." },
  { icon: Ship, title: "Fishing Experience", text: "Experience traditional Maldivian fishing on the open water and enjoy a fun, relaxed trip with the chance to make a great catch." },
  { icon: Map, title: "Island Hopping", text: "Explore another local island, meet the community, walk through island streets and experience more of authentic Maldivian life beyond your guesthouse." },
];

export default function IslandAdventuresPage(){return <main>
<section className="relative min-h-[62vh] overflow-hidden"><Image src="https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?q=80&w=2200&auto=format&fit=crop" alt="Maldives island adventure" fill priority className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-black via-black/70 to-black/30"/><div className="container relative flex min-h-[62vh] items-center"><div className="max-w-3xl py-20"><p className="text-sm font-semibold uppercase tracking-[0.3em] text-gold">Tripelor Experiences</p><h1 className="mt-3 text-5xl font-bold md:text-7xl">Maldives <span className="text-gold">Island Packages</span></h1><p className="mt-6 max-w-2xl text-lg text-gray-200">Choose your perfect five-night escape — from a relaxed half-board snorkeling getaway to a full collection of unforgettable island adventures.</p></div></div></section>

<section className="container py-16"><div className="mb-10 text-center"><p className="text-sm uppercase tracking-[0.3em] text-gold">Choose your escape</p><h2 className="mt-3 text-4xl font-bold">Two ways to experience paradise</h2></div><div className="grid gap-8 lg:grid-cols-2">
<article className="card overflow-hidden"><div className="relative h-64"><Image src="https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1400&auto=format&fit=crop" alt="Maldives snorkeling" fill className="object-cover"/></div><div className="p-7"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-gold">Relax & Snorkel Package</p><h3 className="mt-2 text-3xl font-bold">5 Nights + Half Board + Snorkeling</h3><p className="mt-4 leading-7 text-gray-400">Slow down and enjoy five beautiful nights in the Maldives with your meals taken care of and a snorkeling experience in warm, crystal-clear tropical water. It is a simple, relaxing escape with just the right touch of adventure.</p><div className="mt-6 space-y-3">{["5-night stay","Half Board meal plan","Snorkeling experience"].map(x=><div key={x} className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-gold"/><span>{x}</span></div>)}</div><div className="mt-7 flex flex-wrap items-center justify-between gap-4 border-t border-white/10 pt-6"><strong className="text-4xl text-gold">USD 320</strong><Link href="/booking?package=5-Nights%20Half-Board%20%2B%20Snorkeling%20-%20USD%20320&mealPlan=Half%20Board" className="btn-gold">Book Package</Link></div></div></article>
<article className="card overflow-hidden border-gold/30"><div className="relative h-64"><Image src="https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1400&auto=format&fit=crop" alt="Maldives island adventures" fill className="object-cover"/></div><div className="p-7"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-gold">Full Adventure Package</p><h3 className="mt-2 text-3xl font-bold">5-Night Island Adventure</h3><p className="mt-4 leading-7 text-gray-400">For travelers who want to see and do more: snorkel tropical reefs, escape to a sandbank, search for dolphins, try fishing and explore another local island.</p><div className="mt-6 space-y-3">{["5-night Maldives island experience","Snorkeling trip","Sandbank trip","Dolphin cruise","Fishing experience","Island hopping experience"].map(x=><div key={x} className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-gold"/><span>{x}</span></div>)}</div><div className="mt-7 flex flex-wrap items-center justify-between gap-4 border-t border-white/10 pt-6"><strong className="text-4xl text-gold">USD 540</strong><Link href="/booking?package=5-Night%20Island%20Adventure%20-%20USD%20540" className="btn-gold">Book Package</Link></div></div></article>
</div></section>

<section className="border-y border-white/10 bg-white/[0.02]"><div className="container py-16"><div className="mx-auto max-w-3xl text-center"><Sparkles className="mx-auto h-9 w-9 text-gold"/><p className="mt-4 text-sm uppercase tracking-[0.3em] text-gold">Full Island Adventure</p><h2 className="mt-3 text-4xl font-bold">Five experiences, endless memories</h2><p className="mt-5 text-lg leading-8 text-gray-400">The USD 540 adventure package is made for guests who want to discover a different side of the Maldives each day.</p></div><div className="mt-12 grid gap-6 md:grid-cols-2">{adventures.map(({icon:Icon,title,text})=><article key={title} className="card p-7"><Icon className="h-8 w-8 text-gold"/><h3 className="mt-4 text-2xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-gray-400">{text}</p></article>)}</div></div></section>

<section className="container py-16"><div className="card mx-auto max-w-4xl p-8 md:p-10"><div className="grid gap-8 md:grid-cols-2"><div><Utensils className="h-8 w-8 text-gold"/><h2 className="mt-4 text-3xl font-bold">Prefer a relaxing getaway?</h2><p className="mt-4 leading-7 text-gray-400">Choose the USD 320 package for five nights, Half Board meals and snorkeling. Spend more time relaxing on the island while still enjoying the magic of the Maldivian underwater world.</p></div><div className="flex flex-col justify-center"><div className="flex items-center gap-2 text-gray-400"><Moon className="h-5 w-5 text-gold"/>5 nights</div><div className="mt-3 flex items-center gap-2 text-gray-400"><Utensils className="h-5 w-5 text-gold"/>Half Board</div><div className="mt-3 flex items-center gap-2 text-gray-400"><Waves className="h-5 w-5 text-gold"/>Snorkeling included</div><strong className="mt-5 text-4xl text-gold">USD 320</strong><Link href="/booking?package=5-Nights%20Half-Board%20%2B%20Snorkeling%20-%20USD%20320&mealPlan=Half%20Board" className="btn-gold mt-6">Request This Package</Link></div></div></div></section>
</main>}
