import Image from "next/image";
import Link from "next/link";
import { Waves, Sun, Fish, Ship, Map, CheckCircle2, Moon, Sparkles } from "lucide-react";

const adventures = [
  { icon: Waves, title: "Snorkeling Adventure", text: "Slip into crystal-clear Maldivian waters and discover colorful reef fish, corals and the beautiful underwater world around the islands." },
  { icon: Sun, title: "Sandbank Escape", text: "Spend time on a tiny stretch of white sand surrounded by turquoise ocean — perfect for swimming, relaxing and unforgettable holiday photos." },
  { icon: Fish, title: "Dolphin Cruise", text: "Cruise across the open sea while looking for playful dolphins. Enjoy the ocean breeze, beautiful views and one of the Maldives' most exciting wildlife experiences." },
  { icon: Ship, title: "Fishing Experience", text: "Experience traditional Maldivian fishing on the open water and enjoy a fun, relaxed trip with the chance to make a great catch." },
  { icon: Map, title: "Island Hopping", text: "Explore another local island, meet the community, walk through island streets and experience more of authentic Maldivian life beyond your guesthouse." },
];

export default function IslandAdventuresPage(){return <main>
<section className="relative min-h-[62vh] overflow-hidden"><Image src="https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?q=80&w=2200&auto=format&fit=crop" alt="Maldives island adventure" fill priority className="object-cover"/><div className="absolute inset-0 bg-gradient-to-r from-black via-black/70 to-black/30"/><div className="container relative flex min-h-[62vh] items-center"><div className="max-w-3xl py-20"><p className="text-sm font-semibold uppercase tracking-[0.3em] text-gold">Tripelor Experiences</p><h1 className="mt-3 text-5xl font-bold md:text-7xl">5-Night <span className="text-gold">Island Adventure</span></h1><p className="mt-6 max-w-2xl text-lg text-gray-200">Wake up in paradise and spend your days exploring the ocean, chasing dolphins, snorkeling tropical reefs and discovering the real Maldives.</p><div className="mt-8 flex flex-wrap items-center gap-5"><span className="text-4xl font-bold text-gold">USD 540</span><Link href="/booking?package=5-Night%20Island%20Adventure%20-%20USD%20540" className="btn-gold">Book This Adventure</Link></div></div></div></section>
<section className="container py-16"><div className="mx-auto max-w-3xl text-center"><Sparkles className="mx-auto h-9 w-9 text-gold"/><p className="mt-4 text-sm uppercase tracking-[0.3em] text-gold">More than a holiday</p><h2 className="mt-3 text-4xl font-bold">Five nights full of stories to take home</h2><p className="mt-5 text-lg leading-8 text-gray-400">This package is for travelers who want more than simply staying in a room. Swim in warm tropical water, stand on a sandbank in the middle of the ocean, watch dolphins race beside the boat, try fishing and explore local island life. Every experience gives you a different side of the Maldives.</p></div>
<div className="mt-14 grid gap-6 md:grid-cols-2">{adventures.map(({icon:Icon,title,text})=><article key={title} className="card p-7"><Icon className="h-8 w-8 text-gold"/><h3 className="mt-4 text-2xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-gray-400">{text}</p></article>)}</div></section>
<section className="border-y border-white/10 bg-white/[0.02]"><div className="container grid gap-10 py-16 lg:grid-cols-2"><div><p className="text-sm uppercase tracking-[0.3em] text-gold">Your 5-night escape</p><h2 className="mt-3 text-4xl font-bold">A perfect mix of adventure and relaxation</h2><p className="mt-5 leading-7 text-gray-400">Activities can be arranged around weather and sea conditions so you still have time to relax, enjoy the beach and experience the island at your own pace.</p></div><div className="card p-7"><h3 className="text-2xl font-semibold">Package highlights</h3><div className="mt-5 space-y-4">{["5-night Maldives island experience","Snorkeling trip","Sandbank trip","Dolphin cruise","Fishing experience","Island hopping experience"].map(x=><div key={x} className="flex gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-gold"/><span>{x}</span></div>)}</div><div className="mt-7 border-t border-white/10 pt-6"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-gray-400"><Moon className="h-5 w-5"/>5 Nights</span><strong className="text-3xl text-gold">USD 540</strong></div><Link href="/booking?package=5-Night%20Island%20Adventure%20-%20USD%20540" className="btn-gold mt-6 w-full">Book Island Adventure</Link></div></div></div></section>
<section className="container py-16 text-center"><h2 className="text-4xl font-bold">Ready for your Maldives adventure?</h2><p className="mx-auto mt-4 max-w-2xl text-gray-400">Send your booking request and Tripelor will confirm availability and help arrange your island experience.</p><Link href="/booking?package=5-Night%20Island%20Adventure%20-%20USD%20540" className="btn-gold mt-7">Request This Package</Link></section>
</main>}
