"use client";

import {useEffect,useMemo,useState} from "react";
import {BedDouble,Flame,Heart,Hotel,MapPin,PackageCheck,SearchCheck,Ship,Utensils,Users} from "lucide-react";
import AvailabilityDatePicker from "@/components/availability-date-picker";

const PACKAGE_HOTEL="Uhoo's Lavish Oasis";
const PROPERTY_ROOMS:Record<string,string[]>={
  "Uhoo's Lavish Oasis":["ROOM 101","ROOM 102"],
  "Masfalhi View Inn":["ROOM 101","ROOM 102","ROOM 103","ROOM 104","ROOM 105","ROOM 106"],
  "Rivethi Beach Hotel":["Deluxe Double","Deluxe Twin","Deluxe Double Sea View"]
};
const STANDARD_RATES:Record<string,Record<string,number>>={
  "Uhoo's Lavish Oasis":{"Bed & Breakfast":85,"Half Board":95,"Full Board":115},
  "Masfalhi View Inn":{"Bed & Breakfast":97,"Half Board":110,"Full Board":130}
};
const RIVETHI_RATES:Record<string,Record<string,[number,number]>>={
  "Deluxe Double":{"Room Only":[85,85],"Bed & Breakfast":[95,95]},
  "Deluxe Twin":{"Room Only":[85,85],"Bed & Breakfast":[95,95]},
  "Deluxe Double Sea View":{"Bed & Breakfast":[130,130],"Full Board":[195,195]}
};
function formatDate(date:string){if(!date)return"";return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${date}T00:00:00`));}
function addDays(date:string,days:number){if(!date)return"";const[y,m,d]=date.split("-").map(Number);const x=new Date(Date.UTC(y,m-1,d+days));return`${x.getUTCFullYear()}-${String(x.getUTCMonth()+1).padStart(2,"0")}-${String(x.getUTCDate()).padStart(2,"0")}`;}

export default function BookingPageClientV2(){
 const[propertyName,setPropertyName]=useState(PACKAGE_HOTEL),[packageName,setPackageName]=useState(""),[packagePrice,setPackagePrice]=useState<number|null>(null),[packageNights,setPackageNights]=useState(5),[adults,setAdults]=useState("2"),[children,setChildren]=useState("0"),[checkIn,setCheckIn]=useState(""),[checkOut,setCheckOut]=useState(""),[roomType,setRoomType]=useState("ROOM 101"),[mealPlan,setMealPlan]=useState("Bed & Breakfast"),[fullName,setFullName]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[specialRequests,setSpecialRequests]=useState(""),[speedboatSeats,setSpeedboatSeats]=useState(0),[speedboatTotal,setSpeedboatTotal]=useState(0),[planTotal,setPlanTotal]=useState(0),[sending,setSending]=useState(false),[status,setStatus]=useState(""),[availability,setAvailability]=useState<{available:boolean;rooms_left?:number;total_rooms?:number}|null>(null),[checking,setChecking]=useState(false);
 useEffect(()=>{const p=new URLSearchParams(window.location.search);const property=p.get("property"),meal=p.get("mealPlan"),room=p.get("roomType"),cin=p.get("checkIn"),cout=p.get("checkOut");if(property){setPropertyName(property);setRoomType(PROPERTY_ROOMS[property]?.[0]||"ROOM 101");}if(meal)setMealPlan(meal);if(room)setRoomType(room);if(cin)setCheckIn(cin);if(cout)setCheckOut(cout);setSpeedboatSeats(Number(p.get("speedboatSeats")||0));setSpeedboatTotal(Number(p.get("speedboatTotal")||0));setPlanTotal(Number(p.get("planTotal")||0));const n=Number(p.get("nights")||5);if(n===3||n===5)setPackageNights(n);const pkg=p.get("package")||"";if(pkg){const clean=pkg.replace(/\s*-\s*USD\s*\d+(?:\.\d+)?\s*$/i,"").trim();setPackageName(clean);setPropertyName(PACKAGE_HOTEL);const m=pkg.match(/USD\s*(\d+(?:\.\d+)?)/i);setPackagePrice(m?Number(m[1]):null);setAdults("2");setChildren("0")}},[]);
 useEffect(()=>{if(packageName&&checkIn)setCheckOut(addDays(checkIn,packageNights));},[packageName,checkIn,packageNights]);
 useEffect(()=>{setAvailability(null)},[propertyName,roomType,checkIn,checkOut]);
 useEffect(()=>{if(propertyName==="Rivethi Beach Hotel"){const opts=roomType==="Deluxe Double Sea View"?["Bed & Breakfast","Full Board"]:["Room Only","Bed & Breakfast"];if(!opts.includes(mealPlan))setMealPlan(opts[0]);}},[propertyName,roomType,mealPlan]);
 const isRivethi=propertyName==="Rivethi Beach Hotel";
 const nights=useMemo(()=>{if(!checkIn||!checkOut)return 0;const diff=(new Date(`${checkOut}T00:00:00`).getTime()-new Date(`${checkIn}T00:00:00`).getTime())/86400000;return diff>0?Math.round(diff):0},[checkIn,checkOut]);
 const nightlyRate=useMemo(()=>{if(isRivethi){const pair=RIVETHI_RATES[roomType]?.[mealPlan];return pair?(Number(adults)<=1?pair[0]:pair[1]):0}return STANDARD_RATES[propertyName]?.[mealPlan]||0},[isRivethi,propertyName,roomType,mealPlan,adults]);
 const roomTotal=packageName&&packagePrice?packagePrice:nightlyRate*nights;const estimatedTotal=planTotal||roomTotal+speedboatTotal;
 const location=propertyName===PACKAGE_HOTEL?"V. Felidhoo, Maldives":propertyName==="Rivethi Beach Hotel"?"Hulhumalé, Maldives":"Maldives";
 const roomOptions=PROPERTY_ROOMS[propertyName]||["ROOM 101"];
 const mealOptions=isRivethi?(roomType==="Deluxe Double Sea View"?["Bed & Breakfast","Full Board"]:["Room Only","Bed & Breakfast"]):["Bed & Breakfast","Half Board","Full Board"];
 function handlePropertyChange(v:string){setPropertyName(v);setRoomType(PROPERTY_ROOMS[v]?.[0]||"ROOM 101");setMealPlan("Bed & Breakfast");setAdults("2");setCheckIn("");setCheckOut("");setAvailability(null);setStatus("")}
 function handleCheckIn(v:string){setCheckIn(v);setStatus("");if(packageName&&v)setCheckOut(addDays(v,packageNights));else if(checkOut&&checkOut<=v)setCheckOut("")}
 async function checkAvailability(){setStatus("");if(!checkIn||!checkOut){setStatus("Please select your dates first.");return false}setChecking(true);try{const r=await fetch("/api/availability",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({propertyName,roomType,checkIn,checkOut,rooms:1})});const x=await r.json();if(!r.ok)throw new Error(x?.error||"Unable to check availability.");setAvailability(x);if(!x.available)setStatus("Sorry, no rooms are available for the selected dates.");return Boolean(x.available)}catch(e){setStatus(e instanceof Error?e.message:"Unable to check availability.");return false}finally{setChecking(false)}}
 function validate(){if(!checkIn||!checkOut){setStatus("Please select your check-in and check-out dates.");return false}if(nights<=0){setStatus("Check-out must be after check-in.");return false}if(packageName&&nights!==packageNights){setStatus(`This package is for exactly ${packageNights} nights.`);return false}if(!fullName.trim()){setStatus("Please enter your full name.");return false}if(!email.includes("@")){setStatus("Please enter a valid email address.");return false}if(!phone.trim()){setStatus("Please enter your phone / WhatsApp number.");return false}if(isRivethi&&Number(adults)>2){setStatus("Rivethi room rate supports up to 2 adults per room. Please contact Tripelor for extra-bed arrangements.");return false}return true}
 async function sendBooking(){setStatus("");if(!validate())return;let ok=availability?.available;if(!ok)ok=await checkAvailability();if(!ok)return;setSending(true);try{const finalCheckOut=packageName?addDays(checkIn,packageNights):checkOut;const finalNights=packageName?packageNights:nights;const builderNote=speedboatSeats>0?`Speedboat requested: ${speedboatSeats} seat${speedboatSeats>1?"s":""} at USD 50/person (USD ${speedboatTotal}).`:"";const requestNote=[packageName?`Couple package for 2 adults sharing ${roomType} at ${PACKAGE_HOTEL}.`:specialRequests.trim(),builderNote].filter(Boolean).join(" ");const r=await fetch("/api/booking",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({packageName:packageName||null,packagePrice:packagePrice||null,propertyName:packageName?PACKAGE_HOTEL:propertyName,fullName:fullName.trim(),email:email.trim(),phone:phone.trim(),destination:location,checkIn:formatDate(checkIn),checkOut:formatDate(finalCheckOut),checkInISO:checkIn,checkOutISO:finalCheckOut,nights:finalNights,adults:packageName?"2":adults,children:packageName?"0":children,roomType,rooms:"1",mealPlan,nightlyRate:packageName?null:nightlyRate,estimatedTotal:estimatedTotal||null,speedboatSeats,speedboatTotal,specialRequests:requestNote})});const x=await r.json();if(!r.ok)throw new Error(x?.error||"Unable to send booking request.");const title=packageName||`${propertyName} · ${roomType}`;window.location.href=`/booking/confirmation?name=${encodeURIComponent(fullName.trim())}&title=${encodeURIComponent(title)}&dates=${encodeURIComponent(`${formatDate(checkIn)} – ${formatDate(finalCheckOut)}`)}&ref=${encodeURIComponent(x.bookingReference||x.reservationId||"")}&total=${encodeURIComponent(String(x.finalTotal??estimatedTotal??""))}`;}catch(e){setStatus(e instanceof Error?e.message:"Unable to send booking request.");setAvailability(null)}finally{setSending(false)}}
 return <section className="container py-12 pb-28 md:py-16"><div className="mx-auto max-w-5xl"><p className="text-sm uppercase tracking-[.3em] text-gold">{packageName?"Book This Couple Package":"Book Your Stay"}</p><h1 className="mt-2 text-4xl font-bold md:text-5xl">{packageName?packageName:"Book your Maldives stay"}</h1><p className="mt-4 max-w-2xl text-gray-400">Choose your property, room and dates, check live availability, then send your booking request.</p><div className="mt-10 grid gap-6 lg:grid-cols-[1fr_.38fr]"><form className="card grid gap-6 p-6 md:p-8" onSubmit={e=>e.preventDefault()}>
 {packageName&&<div className="rounded-2xl border border-gold/30 bg-gold/10 p-5"><div className="flex gap-3"><PackageCheck className="mt-1 h-6 w-6 text-gold"/><div><p className="text-xs uppercase tracking-[.2em] text-gold">Selected Couple Package</p><h2 className="mt-1 text-2xl font-bold">{packageName}</h2><p className="mt-2 flex items-center gap-2 text-gray-300"><Heart className="h-4 w-4 text-gold"/>2 adults · 1 room · {packageNights} nights</p></div></div></div>}
 {!packageName&&<div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2 text-sm"><span className="flex items-center gap-2"><Hotel className="h-4 w-4 text-gold"/>Property</span><select value={propertyName} onChange={e=>handlePropertyChange(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3"><option>Uhoo&apos;s Lavish Oasis</option><option>Masfalhi View Inn</option><option>Rivethi Beach Hotel</option></select></label><div className="grid gap-2 text-sm"><span className="flex items-center gap-2"><MapPin className="h-4 w-4 text-gold"/>Location</span><div className="rounded-xl border border-white/10 bg-black px-4 py-3">{location}</div></div></div>}
 <div className="grid gap-5 md:grid-cols-2"><AvailabilityDatePicker label="Check-in" value={checkIn} onChange={handleCheckIn} propertyName={propertyName} roomType={roomType}/><AvailabilityDatePicker label="Check-out" value={checkOut} onChange={setCheckOut} propertyName={propertyName} roomType={roomType} minDate={checkIn?addDays(checkIn,1):undefined} disabled={!!packageName}/></div>
 <div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2 text-sm"><span className="flex items-center gap-2"><BedDouble className="h-4 w-4 text-gold"/>Room</span><select value={roomType} onChange={e=>setRoomType(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3">{roomOptions.map(room=><option key={room}>{room}</option>)}</select></label><label className="grid gap-2 text-sm"><span className="flex items-center gap-2"><Utensils className="h-4 w-4 text-gold"/>Meal plan</span><select value={mealPlan} disabled={!!packageName} onChange={e=>setMealPlan(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3 disabled:opacity-70">{mealOptions.map(x=><option key={x}>{x}</option>)}</select></label></div>
 {!packageName&&<div className="grid gap-5 md:grid-cols-2"><label className="grid gap-2 text-sm"><span className="flex items-center gap-2"><Users className="h-4 w-4 text-gold"/>Adults</span><select value={adults} onChange={e=>setAdults(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3">{(isRivethi?[1,2]:[1,2,3,4]).map(n=><option key={n}>{n}</option>)}</select></label><label className="grid gap-2 text-sm"><span className="flex items-center gap-2"><Users className="h-4 w-4 text-gold"/>Children</span><select value={children} onChange={e=>setChildren(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3">{[0,1,2,3].map(n=><option key={n}>{n}</option>)}</select></label></div>}
 {isRivethi&&<div className="rounded-xl border border-emerald-500/20 bg-emerald-500/[.06] p-4 text-sm text-gray-300"><b className="text-emerald-300">Rivethi live booking enabled.</b> Tripelor currently tracks the hotel’s 18-room pooled inventory. Room-category confirmation remains subject to final hotel reconciliation.</div>}
 <button type="button" onClick={checkAvailability} disabled={checking||!checkIn||!checkOut} className="btn-outline gap-2 disabled:opacity-50"><SearchCheck className="h-4 w-4"/>{checking?"Checking...":"Check Live Availability"}</button>
 {availability?.available&&availability.rooms_left===1&&<div className="rounded-xl border border-gold/40 bg-gold/10 p-4"><Flame className="h-5 w-5 text-gold"/><p className="font-bold text-gold">ONLY 1 ROOM LEFT</p></div>}
 {availability&&<div className={`rounded-xl border p-4 text-sm ${availability.available?"border-green-500/30 text-green-200":"border-red-500/30 text-red-200"}`}>{availability.available?`${roomType} is available · ${availability.rooms_left??""} room${availability.rooms_left===1?"":"s"} left for these dates.`:"Sold out for the selected dates."}</div>}
 <div className="grid gap-5 md:grid-cols-3"><input value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="Full name" className="rounded-xl border border-white/10 bg-black px-4 py-3"/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" type="email" className="rounded-xl border border-white/10 bg-black px-4 py-3"/><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone / WhatsApp" className="rounded-xl border border-white/10 bg-black px-4 py-3"/></div>
 {!packageName&&<textarea value={specialRequests} onChange={e=>setSpecialRequests(e.target.value)} rows={4} placeholder="Airport transfer, honeymoon setup, extra bed or other requests" className="rounded-xl border border-white/10 bg-black px-4 py-3"/>}
 {status&&<div className="rounded-xl border border-white/10 bg-white/[.04] px-4 py-3 text-sm">{status}</div>}
 </form><aside className="card h-fit border-gold/30 p-6 lg:sticky lg:top-24"><p className="text-xs uppercase tracking-[.22em] text-gold">Booking Summary</p><h2 className="mt-2 text-2xl font-bold">{packageName||propertyName}</h2><div className="mt-5 space-y-2 text-sm text-gray-300"><p>{roomType}</p><p>{nights?`${nights} night${nights===1?"":"s"}`:"Select dates"}</p><p>{mealPlan}</p>{nightlyRate>0&&<p>USD {nightlyRate} / night</p>}</div><div className="mt-5 border-t border-white/10 pt-5"><p className="text-sm text-gray-400">Estimated total</p><p className="mt-1 text-3xl font-bold text-gold">USD {estimatedTotal||0}</p></div>{speedboatSeats>0&&<p className="mt-3 flex items-center gap-2 text-xs text-gray-400"><Ship className="h-4 w-4 text-gold"/>{speedboatSeats} speedboat seat(s) included in estimate</p>}<button type="button" onClick={sendBooking} disabled={sending} className="btn-gold mt-6 w-full">{sending?"Sending...":"Request Booking"}</button><p className="mt-3 text-xs leading-5 text-gray-500">No automatic charge. Tripelor confirms the reservation and payment instructions after review.</p></aside></div></div></section>
}
