"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
const props=[{name:"Uhoo's Lavish Oasis",rooms:["ROOM 101","ROOM 102"]},{name:"Masfalhi View Inn",rooms:["ROOM 101","ROOM 102","ROOM 103","ROOM 104","ROOM 105","ROOM 106"]}];
const fmt=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
export default function HomeLiveAvailability(){const now=new Date(),next=new Date(Date.now()+86400000);const [cin,setCin]=useState(fmt(now));const [cout,setCout]=useState(fmt(next));const [counts,setCounts]=useState<Record<string,number>>({});const [loading,setLoading]=useState(false);
async function check(){if(!cin||!cout||cout<=cin)return;setLoading(true);const out:Record<string,number>={};for(const p of props){const r=await Promise.all(p.rooms.map(async room=>{try{const x=await fetch("/api/availability",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({propertyName:p.name,roomType:room,checkIn:cin,checkOut:cout,rooms:1})});const j=await x.json();return x.ok&&j.available!==false}catch{return false}}));out[p.name]=r.filter(Boolean).length}setCounts(out);setLoading(false)}
useEffect(()=>{check()},[]);
return <section className="relative z-10 -mt-8"><div className="container"><div className="rounded-3xl border border-gold/25 bg-black p-5 shadow-2xl md:p-7"><p className="text-sm font-semibold uppercase tracking-[.25em] text-gold">● Live Room Availability</p><div className="mt-4 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><label className="grid gap-1 text-xs text-gray-400">Check-in<input type="date" value={cin} onChange={e=>setCin(e.target.value)} className="rounded-xl border border-white/10 bg-zinc-950 px-4 py-3 text-base text-white"/></label><label className="grid gap-1 text-xs text-gray-400">Check-out<input type="date" value={cout} onChange={e=>setCout(e.target.value)} className="rounded-xl border border-white/10 bg-zinc-950 px-4 py-3 text-base text-white"/></label><button onClick={check} disabled={loading||cout<=cin} className="btn-gold self-end">{loading?"Checking...":"Check Dates"}</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{props.map(p=>{const n=counts[p.name];return <div key={p.name} className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><p className="text-sm text-gray-400">{p.name}</p><h3 className={`mt-1 text-xl font-bold ${n===1?"text-gold":n===0?"text-red-300":"text-emerald-300"}`}>{n===undefined?"Checking live rooms...":n===0?"Sold out for these dates":n===1?"🔥 Only 1 room left":`${cin===fmt(now)?"Tonight: ":""}${n} rooms available`}</h3><Link href={`/booking?property=${encodeURIComponent(p.name)}&mealPlan=Bed%20%26%20Breakfast&checkIn=${cin}&checkOut=${cout}`} className="btn-gold mt-4">{n===0?"Try Other Dates":"Book Now"}</Link></div>})}</div><p className="mt-4 text-xs text-gray-500">Live availability can change until your reservation is confirmed.</p></div></div></section>}
