"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { AdminHostQuestion, HostQuestion } from "@/lib/host-questions";
import HostAudio from "@/components/host-audio";
import HostMediaUpload from "@/components/host-media-upload";
const field="w-full rounded-xl border border-white/20 bg-[#071922] p-3 outline-none focus:border-gold";
const date=(value:string)=>new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeZone:"Indian/Maldives"}).format(new Date(value));
export default function HostQuestionInbox({admin=false}:{admin?:boolean}){
  const [rows,setRows]=useState<AdminHostQuestion[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const [filter,setFilter]=useState("pending"),[offset,setOffset]=useState(0),[hasMore,setHasMore]=useState(false),[editing,setEditing]=useState<string|null>(null);
  const endpoint=admin?"/api/admin/host-questions":"/api/host-questions";
  async function load(page=offset,selection=filter){setLoading(true);setError("");try{const res=await fetch(endpoint+"?offset="+page+(admin?"&filter="+selection:""),{cache:"no-store"});const data=await res.json();if(!res.ok)throw new Error(data.error||"Unable to load questions.");setRows(data.questions);setHasMore(data.hasMore);setOffset(page);setFilter(selection);setEditing(null);}catch(e){setError(e instanceof Error?e.message:"Unable to load questions.");}finally{setLoading(false);}}
  useEffect(()=>{void load(0);},[]);
  return <section className="container py-10 pb-32 md:py-16">
    <p className="eyebrow">{admin?"Tripelor inbox":"A Message From Your Island"}</p><h1 className="mt-4 text-3xl font-semibold md:text-5xl">{admin?"Host Questions":"My Host Messages"}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-gray-300">{admin?"Coordinate replies with each property's host. Publish a reply only when it is ready for the guest to read or hear.":"Your private questions and replies, coordinated by Tripelor. Refresh this page to check for new replies."}</p>
    <div className="mt-6 flex flex-wrap items-center gap-3"><Link href={admin?"/admin":"/account"} className="btn-outline min-h-11">{admin?"Back to admin":"Back to My Trip"}</Link><button disabled={loading} onClick={()=>load()} className="btn-outline min-h-11 disabled:opacity-50">{loading?"Loading…":"Refresh messages"}</button>{admin&&<label className="flex min-h-11 items-center gap-3 text-sm">Show<select disabled={loading} value={filter} onChange={e=>load(0,e.target.value)} className={field}><option value="pending">Awaiting reply</option><option value="answered">Answered</option><option value="all">All questions</option></select></label>}</div>
    {error&&<p role="alert" className="mt-5 rounded-xl border border-red-400/30 p-4 text-sm text-red-200">{error}</p>}
    {!loading&&!error&&rows.length===0&&<div className="mt-7 rounded-2xl border border-white/15 p-7"><p className="text-gray-300">{admin?"No questions in this view.":"No host questions yet. Open a property, meet its host and ask what you would like to know."}</p>{!admin&&<Link href="/stays" className="btn-gold mt-4">Explore stays</Link>}</div>}
    <div className="mt-7 space-y-6">{rows.map(row=><article key={row.id} className="min-w-0 rounded-2xl border border-white/15 bg-white/[.025] p-5 md:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-gold">{row.topic} · {date(row.created_at)}</p><h2 className="mt-2 text-xl font-semibold">{row.property_name}</h2>{admin&&<p className="mt-2 break-words text-xs text-gray-400">{row.guest_name || "Guest"} · {row.guest_email}</p>}</div><span className="rounded-full border border-gold/25 px-3 py-2 text-xs text-gold">{row.replied_at?"Reply ready":"Awaiting reply"}</span></div><p className="mt-5 whitespace-pre-line break-words text-sm leading-7 text-gray-200">{row.question}</p>
      {row.replied_at?<PublishedReply row={row}/>:<p className="mt-5 text-sm leading-7 text-gray-400">{admin?"This guest is waiting for a reply.":"Tripelor has your question and will coordinate a reply with the host. Your reply will appear here."}</p>}
      {admin&&(editing===row.id?<ReplyEditor key={row.id} question={row} onSaved={saved=>setRows(current=>current.map(r=>r.id===saved.id?saved:r))} onClose={()=>setEditing(null)}/>:<button type="button" onClick={()=>setEditing(row.id)} className="btn-gold mt-5">{row.replied_at?"Edit reply":"Write a reply"}</button>)}
    </article>)}</div>
    <div className="mt-7 flex items-center gap-4"><button disabled={loading||offset===0} onClick={()=>load(Math.max(0,offset-20))} className="btn-outline min-h-11 disabled:opacity-40">Previous</button><span className="text-sm text-gray-400">Page {offset/20+1}</span><button disabled={loading||!hasMore} onClick={()=>load(offset+20)} className="btn-outline min-h-11 disabled:opacity-40">Next</button></div>
  </section>;
}
function PublishedReply({row}:{row:HostQuestion}){return <div className="mt-5 rounded-xl border border-gold/20 bg-gold/5 p-5"><p className="text-sm font-semibold text-gold">{row.reply_name} · {row.replied_at?date(row.replied_at):"Reply preview"}</p>{row.reply_text&&<p className="mt-3 whitespace-pre-line break-words text-sm leading-7 text-gray-200">{row.reply_text}</p>}{row.reply_audio&&<div className="mt-4"><HostAudio file={row.reply_audio} label={"Voice reply from "+row.reply_name}/><h3 className="mt-4 text-sm font-semibold">Voice transcript</h3><p className="mt-2 whitespace-pre-line break-words text-sm leading-7 text-gray-200">{row.reply_transcript}</p></div>}</div>;}
function ReplyEditor({question,onSaved,onClose}:{question:AdminHostQuestion;onSaved:(value:AdminHostQuestion)=>void;onClose:()=>void}){
  const [name,setName]=useState(question.draft_name),[text,setText]=useState(question.draft_text),[audio,setAudio]=useState(question.draft_audio),[transcript,setTranscript]=useState(question.draft_transcript);
  const [uploading,setUploading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[preview,setPreview]=useState(false);
  const busy=uploading||saving;
  async function save(action:"draft"|"publish"){if(busy)return;setSaving(true);setError("");setNotice("");try{const res=await fetch("/api/admin/host-questions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:question.id,version:question.version,action,name,text,audio,transcript})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Unable to save reply.");onSaved(data.question);setNotice(action==="draft"?"Draft saved. The guest cannot see these edits yet.":"Reply published to this guest's Host Messages.");}catch(e){setError(e instanceof Error?e.message:"Unable to save reply.");}finally{setSaving(false);}}
  return <div className="mt-6 border-t border-white/15 pt-5"><h3 className="font-semibold">{question.replied_at?"Update this reply":"Reply to this guest"}</h3><p className="mt-2 text-xs leading-6 text-gray-400">Use the name of the person who wrote or recorded the reply. Publishing shows it only to this guest in their account.</p><fieldset disabled={busy} className="mt-4 grid min-w-0 gap-4"><label className="grid gap-2 text-sm">Reply author<input maxLength={120} value={name} onChange={e=>setName(e.target.value)} className={field} placeholder="Host's name or Tripelor team"/></label><label className="grid gap-2 text-sm">Personal reply<textarea rows={5} maxLength={5000} value={text} onChange={e=>setText(e.target.value)} className={field}/></label></fieldset><div className="mt-4"><HostMediaUpload kind="reply" section="audio" questionId={question.id} value={audio} onChange={setAudio} onBusyChange={setUploading} disabled={busy}/></div><label className="mt-4 grid gap-2 text-sm">Voice transcript<textarea disabled={busy} rows={4} maxLength={5000} value={transcript} onChange={e=>setTranscript(e.target.value)} className={field}/></label>
    {error&&<p role="alert" className="mt-4 text-sm text-red-200">{error}</p>}<p role="status" className="mt-4 text-sm text-gold">{notice}</p><div className="mt-4 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>setPreview(v=>!v)} className="btn-outline min-h-11 disabled:opacity-50">{preview?"Hide preview":"Preview reply"}</button><button disabled={busy} onClick={()=>save("draft")} className="btn-outline min-h-11 disabled:opacity-50">Save draft</button><button disabled={busy} onClick={()=>save("publish")} className="btn-gold min-h-11 disabled:opacity-50">Publish reply to guest</button><button disabled={busy} onClick={onClose} className="min-h-11 px-3 text-sm text-gray-400">Close editor</button></div>
    {preview&&<PublishedReply row={{...question,reply_name:name,reply_text:text,reply_audio:audio,reply_transcript:transcript,replied_at:null}}/>}
  </div>;
}
