"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import type { PropertyHost } from "@/lib/property-model";
import { hostMediaUrl, hostTopics } from "@/lib/host-questions";
import HostAudio from "@/components/host-audio";
export default function PropertyHostMessage({host,propertyId,propertyName,slug,preview=false}:{host?:PropertyHost;propertyId:string;propertyName:string;slug:string;preview?:boolean}){
  const [open,setOpen]=useState(false),[topic,setTopic]=useState<string>("Room"),[question,setQuestion]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[sent,setSent]=useState(false),[signIn,setSignIn]=useState(false);
  const draftKey="tripelor-host-question-"+propertyId;
  useEffect(()=>{if(preview)return;try{const saved=JSON.parse(sessionStorage.getItem(draftKey)||"{}");if(typeof saved.question==="string"){setQuestion(saved.question.slice(0,1500));setOpen(true);}if(hostTopics.includes(saved.topic))setTopic(saved.topic);}catch{}},[draftKey,preview]);
  if(!host?.enabled)return null;
  async function submit(e:React.FormEvent){e.preventDefault();if(preview||busy)return;setBusy(true);setError("");setSignIn(false);
    try{const res=await fetch("/api/host-questions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({propertyId,topic,question})});const data=await res.json();if(res.status===401){setSignIn(true);try{sessionStorage.setItem(draftKey,JSON.stringify({topic,question}));}catch{}return;}if(!res.ok)throw new Error(data.error||"Unable to send your question.");setSent(true);setQuestion("");try{sessionStorage.removeItem(draftKey);}catch{}}
    catch(e){setError(e instanceof Error?e.message:"Unable to send your question.");}finally{setBusy(false);}
  }
  return <section id="island-host" aria-labelledby="island-host-title" className="container scroll-mt-28 py-10 md:py-16"><div className="rounded-3xl border border-gold/25 bg-[#0b2731] p-6 md:p-10">
    <p className="text-xs uppercase tracking-[.2em] text-gold">Meet the person behind your stay</p><h2 id="island-host-title" className="font-display mt-3 text-3xl md:text-4xl">A Message From Your Island</h2>
    <div className="mt-7 grid gap-6 sm:grid-cols-[128px_1fr]">{host.photo?<img src={hostMediaUrl(host.photo)} alt={host.name+", your host at "+propertyName} loading="lazy" className="h-32 w-32 rounded-2xl object-cover"/>:<div className="h-32 w-32 rounded-2xl bg-white/5"/>}<div className="min-w-0"><h3 className="text-xl font-semibold">{host.name||"Your island host"}</h3><p className="mt-1 text-sm text-gold">{propertyName}</p><p className="mt-4 whitespace-pre-line break-words text-sm leading-7 text-gray-200">{host.introduction}</p>{host.audio&&<div className="mt-5 max-w-xl"><p className="mb-3 text-sm text-gold">Listen to your host</p><HostAudio file={host.audio} label={"Voice welcome from "+host.name}/><details className="mt-3"><summary className="min-h-11 cursor-pointer py-3 text-sm text-gold">Read the transcript</summary><p className="whitespace-pre-line break-words text-sm leading-7 text-gray-200">{host.transcript||"Transcript not added yet."}</p></details></div>}</div></div>
    <p className="mt-6 text-sm leading-7 text-gray-300">Have a question about the room, food, beach or travelling with children? Tripelor will coordinate a personal reply. Your question and reply stay in your account. Tripelor handles your booking and payment.</p>
    <button type="button" disabled={preview} onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-controls="host-question-form" className="btn-gold mt-5 disabled:opacity-50">{preview?"Ask the host · Preview":open?"Close question form":"Ask the host a question"}</button>
    {open&&!preview&&<div id="host-question-form" className="mt-6 max-w-2xl rounded-2xl border border-white/15 p-5">{sent?<div role="status"><p className="font-semibold text-gold">Your question is with Tripelor.</p><p className="mt-2 text-sm leading-6 text-gray-300">We’ll coordinate the reply with your host. You can check for it in My Trip → Host Messages.</p><Link className="btn-outline mt-4 min-h-11" href="/account/host-questions">View my host messages</Link></div>:<form onSubmit={submit} className="space-y-4"><label className="grid gap-2 text-sm">What would you like to know?<select disabled={busy} value={topic} onChange={e=>setTopic(e.target.value)} className="rounded-xl border border-white/20 bg-[#071922] p-3">{hostTopics.map(t=><option key={t}>{t}</option>)}</select></label><label className="grid gap-2 text-sm">Your question<textarea disabled={busy} value={question} onChange={e=>setQuestion(e.target.value)} required maxLength={1500} rows={4} className="rounded-xl border border-white/20 bg-[#071922] p-3"/></label><p className="text-xs leading-6 text-gray-400">Sign in to send and receive a private reply. Please leave payment details and sensitive documents out of your question.</p>{error&&<p role="alert" className="text-sm text-red-200">{error}</p>}{signIn&&<p role="status" className="text-sm text-gold">Your question is saved in this browser tab. <Link href={"/login?next="+encodeURIComponent("/stays/"+slug+"#island-host")} className="underline">Sign in to continue</Link>.</p>}<button disabled={busy||!question.trim()} className="btn-gold disabled:opacity-50">{busy?"Sending…":"Send question"}</button></form>}</div>}
  </div></section>;
}
