"use client";
import Link from "next/link";
import {Award,Gift,Sparkles,Star,TrendingUp} from "lucide-react";

export default function Rewards2Card({user,loyalty}:{user:{fullName?:string;email:string};loyalty:any}){
 const points=Number(loyalty?.account?.points_balance||0);const lifetime=Number(loyalty?.account?.lifetime_points||points);const tx=Array.isArray(loyalty?.transactions)?loyalty.transactions:[];
 const tier=lifetime>=3000?"Gold":lifetime>=1000?"Silver":"Bronze";const next=tier==="Bronze"?1000:tier==="Silver"?3000:null;const floor=tier==="Bronze"?0:tier==="Silver"?1000:3000;const progress=next?Math.max(0,Math.min(100,((lifetime-floor)/(next-floor))*100)):100;const toNext=next?Math.max(0,next-lifetime):0;const free=Math.floor(points/1000);
 return <section className="mt-8 grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
  <div className="relative min-h-[260px] overflow-hidden rounded-[2rem] border border-gold/35 bg-gradient-to-br from-zinc-800 via-black to-[#211b08] p-6 shadow-[0_20px_80px_rgba(0,0,0,.45)] sm:p-8"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-gold/15 blur-3xl"/><div className="relative flex h-full flex-col justify-between gap-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.3em] text-gold">Tripelor Rewards</p><h2 className="mt-2 text-2xl font-bold">{user.fullName||"Tripelor Member"}</h2><p className="mt-1 text-xs text-gray-500">{user.email}</p></div><div className="rounded-full border border-gold/30 bg-gold/10 px-4 py-2 text-sm font-semibold text-gold">{tier}</div></div><div><p className="text-sm text-gray-400">Available balance</p><div className="mt-1 flex items-end gap-2"><strong className="text-5xl text-gold">{points}</strong><span className="pb-1 text-gray-400">points</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-gold transition-all" style={{width:`${progress}%`}}/></div><div className="mt-2 flex justify-between gap-3 text-xs text-gray-400"><span>{tier} Member</span><span>{next?`${toNext} points to ${tier==="Bronze"?"Silver":"Gold"}`:"Top tier achieved"}</span></div></div></div></div>
  <div className="grid gap-5 sm:grid-cols-2"><div className="card p-5"><div className="flex items-center gap-2 text-gold"><Gift className="h-5 w-5"/><h3 className="font-semibold">Available rewards</h3></div>{free>0?<><p className="mt-4 text-3xl font-bold">{free} free night{free>1?"s":""}</p><p className="mt-2 text-sm text-gray-400">Every 1,000 available points can be redeemed for one free night, subject to room availability.</p><a href="https://wa.me/9609429403?text=Hello%20Tripelor%2C%20I%20would%20like%20to%20redeem%20my%20Tripelor%20Rewards." className="btn-gold mt-4 w-full">Redeem Reward</a></>:<><p className="mt-4 text-xl font-bold">{1000-(points%1000)} points to a free night</p><p className="mt-2 text-sm text-gray-400">Keep earning with completed Tripelor stays.</p><Link href="/booking" className="btn-outline mt-4 w-full">Book & Earn</Link></>}</div><div className="card p-5"><div className="flex items-center gap-2 text-gold"><TrendingUp className="h-5 w-5"/><h3 className="font-semibold">How you earn</h3></div><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between gap-3"><span className="text-gray-300">Completed room nights</span><b className="text-gold">100 pts/night</b></div><div className="flex justify-between gap-3"><span className="text-gray-400">Speedboat transfers</span><span className="text-xs text-gray-500">Coming soon</span></div><div className="flex justify-between gap-3"><span className="text-gray-400">Experiences & bundles</span><span className="text-xs text-gray-500">Coming soon</span></div></div><p className="mt-4 text-xs text-gray-500">Only completed eligible purchases earn points. Future earning categories will appear here when activated.</p></div></div>
  <div className="card p-5 xl:col-span-2"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Award className="h-5 w-5 text-gold"/><h3 className="font-semibold">Recent points activity</h3></div><div className="flex items-center gap-1 text-xs text-gray-500"><Star className="h-3.5 w-3.5"/>{lifetime} lifetime points</div></div>{tx.length===0?<p className="mt-4 text-sm text-gray-500">No points activity yet. Complete your first eligible stay to start earning.</p>:<div className="mt-4 grid gap-3 md:grid-cols-2">{tx.slice(0,6).map((t:any)=><div key={t.id} className="flex items-center justify-between gap-4 rounded-xl border border-white/10 bg-white/[.025] p-4"><div><p className="text-sm font-medium">{t.description||"Tripelor Rewards activity"}</p><p className="mt-1 text-xs text-gray-500">{t.created_at?new Date(t.created_at).toLocaleDateString("en-GB"):""}</p></div><strong className={Number(t.points)>=0?"text-emerald-300":"text-red-300"}>{Number(t.points)>=0?"+":""}{Number(t.points)} pts</strong></div>)}</div>}</div>
 </section>
}
