"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {Flame,Heart,Clock3,CalendarDays,ArrowRight} from "lucide-react";
const hotels=[{name:"Uhoo's Lavish Oasis",rooms:["ROOM 101","ROOM 102"]},{name:"Masfalhi View Inn",rooms:["ROOM 101","ROOM 102","ROOM 103","ROOM 104","ROOM 105","ROOM 106"]}];
const fmt=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const add=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return fmt(d)};
export default function SmartOffers(){const[availability,setAvailability]=useState<Record<string,number>>({});const today=fmt(new Date()),tomorrow=add(1),lastMinuteEnd=add(3);
useEffect(()=>{(async()=>{const out:Record<string,number>={};for(const h of hotels){const a=await Promise.all(h.rooms.map(async room=>{try{const r=await fetch("/api/availability",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({propertyName:h.name,roomType:room,checkIn:today,checkOut:tomorrow,rooms:1})});const x=await r.json();return r.ok&&x.available!==false}catch{return false}}));out[h.name]=a.filter(Boolean).length}setAvailability(out)})()},[]);
const scarce=hotels.find(h=>availability[h.name]===1);const lastMinute=hotels.find(h=>(availability[h.name]??0)>0);
return <section className="border-y border-white/10 bg-[#070707]"><div className="container py-16"><div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="text-sm uppercase tracking-[.3em] text-gold">Smart Offers</p><h2 className="mt-2 text-3xl font-bold md:text-4xl">A better reason to book now</h2><p className="mt-2 text-gray-400">Offers and urgency are shown only when they match current Tripelor availability.</p></div><Link href="/island-adventures?duration=5" className="text-sm font-semibold text-gold">View all packages →</Link></div><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
{scarce&&<Link href={`/booking?property=${encodeURIComponent(scarce.name)}&checkIn=${today}&checkOut=${tomorrow}`} className="group rounded-3xl border border-red-500/25 bg-red-500/[.07] p-6"><Flame className="h-7 w-7 text-red-300"/><p className="mt-5 text-xs uppercase tracking-[.2em] text-red-300">Live availability</p><h3 className="mt-2 text-2xl font-bold">Only 1 room left tonight</h3><p className="mt-2 text-sm text-gray-400">{scarce.name}</p><span className="mt-5 flex items-center gap-2 font-semibold text-gold">Book this room <ArrowRight className="h-4 w-4"/></span></Link>}
<Link href="/island-adventures?duration=5" className="group rounded-3xl border border-gold/25 bg-gold/[.07] p-6"><CalendarDays className="h-7 w-7 text-gold"/><p className="mt-5 text-xs uppercase tracking-[.2em] text-gold">Longer escape</p><h3 className="mt-2 text-2xl font-bold">Stay 5 nights & experience more</h3><p className="mt-2 text-sm text-gray-400">Explore Tripelor's 5-night island packages with stays and curated experiences.</p><span className="mt-5 flex items-center gap-2 font-semibold text-gold">See 5-night packages <ArrowRight className="h-4 w-4"/></span></Link>
<Link href="/island-adventures?duration=5" className="group rounded-3xl border border-pink-400/20 bg-pink-400/[.05] p-6"><Heart className="h-7 w-7 text-pink-300"/><p className="mt-5 text-xs uppercase tracking-[.2em] text-pink-300">Couples</p><h3 className="mt-2 text-2xl font-bold">Honeymoon Special</h3><p className="mt-2 text-sm text-gray-400">Romantic island stays, sunset experiences and memorable dinners for two.</p><span className="mt-5 flex items-center gap-2 font-semibold text-gold">Explore romantic trips <ArrowRight className="h-4 w-4"/></span></Link>
{lastMinute&&<Link href={`/booking?property=${encodeURIComponent(lastMinute.name)}&checkIn=${today}&checkOut=${lastMinuteEnd}`} className="group rounded-3xl border border-emerald-500/20 bg-emerald-500/[.05] p-6"><Clock3 className="h-7 w-7 text-emerald-300"/><p className="mt-5 text-xs uppercase tracking-[.2em] text-emerald-300">Last-minute availability</p><h3 className="mt-2 text-2xl font-bold">Maldives this week?</h3><p className="mt-2 text-sm text-gray-400">{lastMinute.name} currently has room availability. Check your dates before it changes.</p><span className="mt-5 flex items-center gap-2 font-semibold text-gold">Check availability <ArrowRight className="h-4 w-4"/></span></Link>}
</div></div></section>}
