export type StayPackage={name:string;slug:string;label:string;price:number;image:string;description:string;items:string[];meal:string;nights:number};
const fallback="https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1400&auto=format&fit=crop";
export const fiveNight:StayPackage[]=[
{name:"Maldives Reef & Relax Escape",slug:"reef-relax-escape",label:"Relax & Snorkel",price:750,nights:5,image:"https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1400&auto=format&fit=crop",description:"A relaxing couple escape with Half Board meals and snorkeling in warm, crystal-clear tropical water.",items:["5 nights for 2 adults","1 room at Uhoo's Lavish Oasis","Half Board meal plan","Snorkeling experience"],meal:"Half Board"},
{name:"5-Night Island Adventure",slug:"5-night-island-adventure",label:"Full Adventure",price:1490,nights:5,image:fallback,description:"A five-night couple adventure with Half Board meals, snorkeling, sandbank, dolphins, fishing and island hopping.",items:["5 nights for 2 adults","1 room at Uhoo's Lavish Oasis","Half Board meal plan","Snorkeling + sandbank","Dolphin cruise + fishing","Island hopping"],meal:"Half Board"},
{name:"Maldives Ocean Discovery Escape",slug:"ocean-discovery-escape",label:"Full Board Adventure",price:1290,nights:5,image:"https://images.unsplash.com/photo-1530789253388-582c481c54b0?q=80&w=1400&auto=format&fit=crop",description:"A richer couple escape with Full Board dining, snorkeling, night fishing and island hopping.",items:["5 nights for 2 adults","1 room at Uhoo's Lavish Oasis","Full Board meal plan","Snorkeling","Night fishing + island hopping"],meal:"Full Board"},
{name:"Beach BBQ Dinner Escape",slug:"beach-bbq-dinner-escape",label:"Beach BBQ",price:990,nights:5,image:"https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?q=80&w=1400&auto=format&fit=crop",description:"A romantic couple getaway featuring a special BBQ dinner on the beach, sunset time and snorkeling.",items:["5 nights for 2 adults","1 room at Uhoo's Lavish Oasis","Half Board meal plan","Beach BBQ dinner","Sunset + snorkeling"],meal:"Half Board"},
{name:"Honeymoon Island Escape",slug:"honeymoon-island-escape",label:"Honeymoon",price:1350,nights:5,image:fallback,description:"A romantic honeymoon package with Full Board dining, beach dinner, sandbank time and ocean experiences.",items:["5 nights for 2 adults","1 room at Uhoo's Lavish Oasis","Full Board meal plan","Romantic beach dinner","Sandbank + dolphin cruise"],meal:"Full Board"},
{name:"Manta & Dolphin Adventure",slug:"manta-dolphin-adventure",label:"Marine Adventure",price:1100,nights:5,image:"https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1400&auto=format&fit=crop",description:"A couple ocean adventure with manta excursion when conditions allow, dolphin cruise and snorkeling.",items:["5 nights for 2 adults","1 room at Uhoo's Lavish Oasis","Half Board meal plan","Manta excursion","Dolphin cruise + snorkeling"],meal:"Half Board"},
{name:"Sunset & Sandbank Escape",slug:"sunset-sandbank-escape",label:"Island Romance",price:950,nights:5,image:fallback,description:"A romantic five-night couple getaway with Half Board dining, sandbank time and a sunset cruise.",items:["5 nights for 2 adults","1 room at Uhoo's Lavish Oasis","Half Board meal plan","Sandbank trip","Sunset cruise + snorkeling"],meal:"Half Board"}
];
const threePrices=[550,1250,1050,775,1050,850,725];
export const threeNight:StayPackage[]=fiveNight.map((p,i)=>({...p,name:p.name.replace("5-Night ",""),nights:3,price:threePrices[i],description:p.description.replace(/five-night/gi,"three-night").replace(/five nights/gi,"three nights"),items:p.items.map(x=>x.startsWith("5 nights")?"3 nights for 2 adults":x)}));
