import { requireUser, isAdminEmail } from '@/lib/auth-server';
import { VAAVU_EXCURSIONS } from '@/lib/vaavu-excursions';

export class SharedExcursionError extends Error { constructor(message: string, public status = 400) { super(message); } }
const columns = 'id,excursion_slug,excursion_name,travel_date,price_usd,capacity,joined_guests,status,meeting_note,created_at,updated_at';
async function db(path: string, init: RequestInit = {}) {
  const url = process.env.SUPABASE_URL?.replace(/\/$/, ''), key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new SharedExcursionError('Shared excursions are temporarily unavailable.', 503);
  const response = await fetch(`${url}/rest/v1/${path}`, { ...init, headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json', Prefer: 'return=representation', ...(init.headers || {}) }, cache: 'no-store', signal: AbortSignal.timeout(6000) });
  const result = await response.json().catch(() => null);
  if (!response.ok) {
    const message = String(result?.message || '');
    if (message.includes('GROUP_FULL')) throw new SharedExcursionError('This group is full. Please choose another date.', 409);
    if (message.includes('GROUP_UNAVAILABLE')) throw new SharedExcursionError('This group is no longer accepting requests.', 409);
    throw new SharedExcursionError('Unable to load shared excursions. Please try again.', 503);
  }
  return result;
}
function text(value: unknown, max: number, required = false) { if (typeof value !== 'string' || value.trim().length > max || (required && !value.trim())) throw new SharedExcursionError('Please complete the requested details.'); return value.trim(); }
function date(value: unknown) { if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value) || value < new Date(Date.now() + 5 * 3600000).toISOString().slice(0,10) || !Number.isFinite(Date.parse(value + 'T12:00:00Z'))) throw new SharedExcursionError('Choose a valid future date.'); return value; }
function number(value: unknown, min: number, max: number) { const n = Number(value); if (!Number.isInteger(n) || n < min || n > max) throw new SharedExcursionError(`Choose between ${min} and ${max} guests.`); return n; }
export async function sharedExcursionBody(request: Request) { const origin = request.headers.get('origin'); const host = request.headers.get('host') || new URL(request.url).host; try { const source = new URL(origin || ''); if (source.host !== host || !['http:','https:'].includes(source.protocol)) throw new Error(); } catch { throw new SharedExcursionError('Please use the Tripelor website.', 403); } const raw = await request.text(); if (raw.length > 5000) throw new SharedExcursionError('Request is too large.', 413); try { return JSON.parse(raw); } catch { throw new SharedExcursionError('Send a valid request.'); } }
export function publicGroup(row: any) { return { ...row, price_usd: Number(row.price_usd), spaces_left: Number(row.capacity) - Number(row.joined_guests) }; }
export async function listGroups() { const rows = await db(`shared_excursion_groups?status=in.(open,confirmed)&travel_date=gte.${new Date(Date.now() + 5 * 3600000).toISOString().slice(0,10)}&select=${columns}&order=travel_date.asc,excursion_name.asc`); return rows.map(publicGroup); }
export async function customerJoins(user: any) { const rows = await db(`shared_excursion_joins?user_id=eq.${encodeURIComponent(user.id)}&select=id,group_id,guests,status,created_at,guest_name,guest_email,guest_phone,notes,shared_excursion_groups(${columns})&order=created_at.desc`); return rows; }
export async function joinGroup(user: any, body: any) {
  if (!user.email || !user.email_confirmed_at) throw new SharedExcursionError('Confirm your account email before joining a shared excursion.', 403);
  if (typeof body?.groupId !== 'string' || !/^[0-9a-f-]{36}$/i.test(body.groupId)) throw new SharedExcursionError('Choose a valid shared excursion.');
  const guests = number(body.guests, 1, 20); const phone = text(body.phone || '', 80); const notes = text(body.notes || '', 1000);
  const rows = await db('rpc/join_shared_excursion_group', { method: 'POST', body: JSON.stringify({ p_group_id: body.groupId, p_user_id: user.id, p_guest_name: text(user.user_metadata?.full_name || 'Tripelor customer',160,true), p_guest_email: user.email, p_guest_phone: phone, p_guests: guests, p_notes: notes }) });
  const join = rows[0]; if (!join) throw new SharedExcursionError('Unable to join this group.', 503);
  await notifyAdmin(join, body.groupId); return { request: join };
}
async function notifyAdmin(join: any, groupId: string) { const key = process.env.RESEND_API_KEY; if (!key) return; try { const groups = await db(`shared_excursion_groups?id=eq.${groupId}&select=${columns}&limit=1`); const group = groups[0]; if (!group) return; await fetch('https://api.resend.com/emails', { method:'POST', headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json','Idempotency-Key':`shared-join/${join.id}`}, body: JSON.stringify({ from:'Tripelor Excursions <bookings@tripelor.com>', to:['bookings@tripelor.com'], bcc:['johnshamil87@gmail.com'], reply_to:join.guest_email, subject:`Shared excursion join request · ${group.excursion_name}`, text:`New shared excursion join request\n\n${group.excursion_name}\nDate: ${group.travel_date}\nGuests: ${join.guests}\nCustomer: ${join.guest_name}\nEmail: ${join.guest_email}\nPhone: ${join.guest_phone || 'Not provided'}\nNotes: ${join.notes || 'None'}\n\nReview: https://www.tripelor.com/admin/shared-excursions`}), signal:AbortSignal.timeout(5000) }); } catch { /* request remains visible to admin */ } }
export async function adminGuard() { const user = await requireUser(); if (!isAdminEmail(user.email)) throw new SharedExcursionError('Admin access required.', 403); return user; }
export async function adminGroups() { const groups = await db(`shared_excursion_groups?select=${columns}&order=travel_date.asc,created_at.desc&limit=300`); const joins = await db('shared_excursion_joins?select=*&order=created_at.asc&limit=1000'); return { groups: groups.map(publicGroup), joins }; }
export async function createGroup(body: any) { const slug = text(body.excursionSlug, 100, true); const excursion = VAAVU_EXCURSIONS.find(item => item.slug === slug); if (!excursion) throw new SharedExcursionError('Choose an available excursion.'); const travelDate = date(body.travelDate); const capacity = number(body.capacity, 2, 100); const price = Number(body.priceUsd); if (!Number.isFinite(price) || price < 0 || price > 100000) throw new SharedExcursionError('Enter a valid price.'); return (await db('shared_excursion_groups',{method:'POST',body:JSON.stringify({excursion_slug:excursion.slug,excursion_name:excursion.name,travel_date:travelDate,price_usd:Math.round(price*100)/100,capacity,meeting_note:text(body.meetingNote || '',500)})}))[0]; }
export async function updateGroup(body: any) { if (typeof body.id !== 'string' || !/^[0-9a-f-]{36}$/i.test(body.id)) throw new SharedExcursionError('Choose a valid group.'); const status = String(body.status); if (!['open','confirmed','cancelled','completed'].includes(status)) throw new SharedExcursionError('Choose a valid group status.'); const rows = await db(`shared_excursion_groups?id=eq.${body.id}`,{method:'PATCH',body:JSON.stringify({status,meeting_note:text(body.meetingNote || '',500),updated_at:new Date().toISOString()})}); if (!rows.length) throw new SharedExcursionError('Group not found.',404); if (status === 'confirmed') await notifyJoinedCustomers(body.id, rows[0]); return rows[0]; }
async function notifyJoinedCustomers(groupId: string, group: any) { const key=process.env.RESEND_API_KEY; if (!key) return; const joins=await db(`shared_excursion_joins?group_id=eq.${groupId}&status=eq.pending&select=*`); for (const join of joins) { try { const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json','Idempotency-Key':`shared-confirm/${join.id}`},body:JSON.stringify({from:'Tripelor Excursions <bookings@tripelor.com>',to:[join.guest_email],reply_to:'bookings@tripelor.com',subject:`Your shared excursion is confirmed · ${group.excursion_name}`,text:`Good news — your shared excursion is confirmed.\n\n${group.excursion_name}\nDate: ${group.travel_date}\nGuests in your request: ${join.guests}\nPrice: USD ${group.price_usd} per person\n${group.meeting_note ? `Meeting details: ${group.meeting_note}\n` : ''}\nTripelor will confirm final boat and payment details with you. This email does not guarantee a departure if weather or sea conditions change.`}),signal:AbortSignal.timeout(5000)}); if(response.ok) await db(`shared_excursion_joins?id=eq.${join.id}`,{method:'PATCH',body:JSON.stringify({status:'confirmed',notification_sent_at:new Date().toISOString(),updated_at:new Date().toISOString()})}); } catch { /* retry from admin update if needed */ } } }
export function sharedExcursionResponse(value: unknown, status=200) { return Response.json(value,{status,headers:{'Cache-Control':'no-store'}}); }
export function sharedExcursionError(error: unknown) { if (error instanceof Error && error.message==='UNAUTHORIZED') return sharedExcursionResponse({error:'Please sign in to join a shared excursion.'},401); if(error instanceof SharedExcursionError) return sharedExcursionResponse({error:error.message},error.status); return sharedExcursionResponse({error:'Shared excursion service is temporarily unavailable.'},503); }
