"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Plane,Ship,Users,Mail} from "lucide-react";
const PRICE=50;
type S={day_of_week:number;departure_time:string;operator:string};
const toMin=(t:string)=>{const [h,m]=t.slice(0,5).split(":").map(Number);return h*60+m};
const nice=(t:string)=>new Date(`2000-01-01T${t.slice(0,5)}:00`).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"});
export default function SpeedboatPage(){
 const [date,setDate]=useState("");const [time,setTime]=useState("");const [flight,setFlight]=useState("");const [seats,setSeats]=useState("1");const [name,setName]=useState("");const [email,setEmail]=useState("");const [phone,setPhone]=useState("");const [notes,setNotes]=useState("");const [schedule,setSchedule]=useState<S[]>([]);const [status,setStatus]=useState("");const [sending,setSending]=useState(false);
 useEffect(()=>{fetch("/api/speedboat/schedule").then(r=>r.json()).then(x=>setSchedule(x.schedule||[])).catch(()=>{})},[]);
 const rec=useMemo(()=>{if(!date||!time)return null;const day=new Date(`${date}T12:00:00`).getDay();return schedule.filter(x=>x.day_of_week===day&&toMin(x.departure_time)>=toMin(time)+90).sort((a,b)=>toMin(a.departure_time)-toMin(b.departure_time))[0]||false},[date,time,schedule]);
 async function submit(e:FormEvent){e.preventDefault();setStatus("");const arrival=new Date(`${date}T${time}:00`);if((arrival.getTime()-Date.now())/3600000<24){setStatus("Please request your speedboat at least 24 hours before arrival.");return}setSending(true);try{const r=await fetch("/api/speedboat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({arrivalDate:date,arrivalTime:time,flightNumber:flight,recommendedDeparture:rec&&rec.departure_time||null,seats:Number(seats),pricePerPerson:PRICE,total:Number(seats)*PRICE,fullName:name,email,phone,notes})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to send request");setStatus("Request sent. Tripelor will confirm your speedboat and seats.")}catch(e){setStatus(e instanceof Error?e.message:"Unable to send request")}finally{setSending(false)}}
 return <section className="container py-16 md:py-20"><div className="mx-auto max-w-4xl"><p className="text-sm uppercase tracking-[.3em] text-gold">Airport Transfer</p><h1 className="mt-2 text-4xl font-bold md:text-6xl">Arrival Flight Assistant</h1><p className="mt-4 text-gray-400">Enter your flight arrival details and Tripelor will recommend a suitable Malé → V. Felidhoo speedboat.</p>
 <div className="card mt-8 p-6"><div className="flex items-center gap-2 text-gold"><Plane/> <b>Your flight</b></div><div className="mt-5 grid gap-4 md:grid-cols-3"><input value={flight} onChange={e=>setFlight(e.target.value.toUpperCase())} placeholder="Flight number (e.g. EK652)" className="rounded-xl border border-white/10 bg-black px-4 py-3"/><input required type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3"/><input required type="time" value={time} onChange={e=>setTime(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3"/></div>
 {date&&time&&<div className={`mt-5 rounded-2xl border p-5 ${rec?"border-emerald-500/30 bg-emerald-500/10":"border-amber-500/30 bg-amber-500/10"}`}>{schedule.length===0?<><b>Schedule confirmation required</b><p className="mt-1 text-sm text-gray-300">Send your details and Tripelor will recommend the best transfer.</p></>:rec?<><p className="text-xs uppercase tracking-[.2em] text-emerald-300">Recommended transfer</p><h2 className="mt-1 text-2xl font-bold"><Ship className="mr-2 inline text-gold"/>Dream Speed · {nice(rec.departure_time)}</h2><p className="mt-2 text-sm text-gray-300">Includes approximately 90 minutes after landing for immigration, baggage and airport exit.</p><p className="mt-3 font-semibold text-gold">{seats} passenger{Number(seats)>1?"s":""} · USD {Number(seats)*PRICE}</p></>:<><b>No comfortable same-day connection found</b><p className="mt-1 text-sm text-gray-300">There is no scheduled departure at least 90 minutes after your arrival. Send the request and Tripelor will help with the best option.</p></>}</div>}</div>
 <form onSubmit={submit} className="card mt-6 grid gap-5 p-6"><div className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-gold/30 bg-gold/10 p-4"><b className="text-gold">USD 50 per person</b><p className="mt-1 text-sm text-gray-300">Pay the boat operator or Uhoo&apos;s Lavish Oasis.</p></div><div className="rounded-xl border border-gold/30 bg-gold/10 p-4"><b className="text-gold">Book at least 24 hours ahead</b><p className="mt-1 text-sm text-gray-300">Transfer schedule and seats are subject to confirmation.</p></div></div><label className="grid gap-2"><span className="flex gap-2"><Users className="text-gold"/>Passengers / seats</span><select value={seats} onChange={e=>setSeats(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3">{Array.from({length:20},(_,i)=>i+1).map(n=><option key={n}>{n}</option>)}</select></label><div className="grid gap-4 md:grid-cols-3"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" className="rounded-xl border border-white/10 bg-black px-4 py-3"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className="rounded-xl border border-white/10 bg-black px-4 py-3"/><input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone / WhatsApp" className="rounded-xl border border-white/10 bg-black px-4 py-3"/></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Transfer notes" className="rounded-xl border border-white/10 bg-black px-4 py-3"/>{status&&<div className="rounded-xl bg-white/5 p-4 text-sm">{status}</div>}<button disabled={sending} className="btn-gold w-full md:w-auto"><Mail className="h-5 w-5"/>{sending?"Sending...":"Request Recommended Speedboat"}</button><p className="text-xs text-gray-500">Recommendation uses the Tripelor schedule plus a 90-minute airport allowance. Final departure and seat availability require confirmation.</p></form></div></section>}
