"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {Plane,Ship,Users,Mail,Search,CheckCircle2,AlertTriangle} from "lucide-react";
const PRICE=50;
type S={day_of_week:number;departure_time:string;operator:string};
type FlightInfo={flightNumber:string;airline:string|null;status:string|null;origin:string|null;originIata:string|null;arrivalAirport:string|null;arrivalIata:string|null;arrivalDate:string;arrivalTime:string;terminal:string|null;gate:string|null;scheduled:string|null;estimated:string|null;actual:string|null};
const toMin=(t:string)=>{const [h,m]=t.slice(0,5).split(":").map(Number);return h*60+m};
const nice=(t:string)=>new Date(`2000-01-01T${t.slice(0,5)}:00`).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"});
export default function SpeedboatPage(){
 const [date,setDate]=useState("");const [time,setTime]=useState("");const [flight,setFlight]=useState("");const [seats,setSeats]=useState("1");const [name,setName]=useState("");const [email,setEmail]=useState("");const [phone,setPhone]=useState("");const [notes,setNotes]=useState("");const [schedule,setSchedule]=useState<S[]>([]);const [status,setStatus]=useState("");const [sending,setSending]=useState(false);const [lookup,setLookup]=useState(false);const [flightInfo,setFlightInfo]=useState<FlightInfo|null>(null);const [lookupStatus,setLookupStatus]=useState("");
 useEffect(()=>{fetch("/api/speedboat/schedule").then(r=>r.json()).then(x=>setSchedule(x.schedule||[])).catch(()=>{});fetch("/api/auth/me",{cache:"no-store"}).then(r=>r.json()).then(x=>{if(!x?.user)return;setName(v=>v||x.user.fullName||"");setEmail(v=>v||x.user.email||"")}).catch(()=>{})},[]);
 const rec=useMemo(()=>{if(!date||!time)return null;const day=new Date(`${date}T12:00:00`).getDay();return schedule.filter(x=>x.day_of_week===day&&toMin(x.departure_time)>=toMin(time)+90).sort((a,b)=>toMin(a.departure_time)-toMin(b.departure_time))[0]||false},[date,time,schedule]);
 async function lookupFlight(){setLookupStatus("");setFlightInfo(null);if(!flight.trim()){setLookupStatus("Enter your flight number first.");return}setLookup(true);try{const q=new URLSearchParams({flight:flight.trim()});if(date)q.set("date",date);const r=await fetch(`/api/flight-lookup?${q.toString()}`,{cache:"no-store"});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to find this flight.");setFlightInfo(x.flight);setFlight(x.flight.flightNumber||flight);setDate(x.flight.arrivalDate);setTime(x.flight.arrivalTime);setLookupStatus("Flight found. Arrival date and time filled automatically.");}catch(e){setLookupStatus(e instanceof Error?e.message:"Unable to find this flight.");}finally{setLookup(false)}}
 async function submit(e:FormEvent){e.preventDefault();setStatus("");const arrival=new Date(`${date}T${time}:00`);if((arrival.getTime()-Date.now())/3600000<24){setStatus("Please request your speedboat at least 24 hours before arrival.");return}setSending(true);try{const r=await fetch("/api/speedboat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({arrivalDate:date,arrivalTime:time,flightNumber:flight,recommendedDeparture:rec&&rec.departure_time||null,seats:Number(seats),pricePerPerson:PRICE,total:Number(seats)*PRICE,fullName:name,email,phone,notes})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Unable to send request");setStatus("Request sent. Tripelor will confirm your speedboat and seats.")}catch(e){setStatus(e instanceof Error?e.message:"Unable to send request")}finally{setSending(false)}}
 return <section className="container py-16 md:py-20"><div className="mx-auto max-w-4xl"><p className="text-sm uppercase tracking-[.3em] text-gold">Airport Transfer</p><h1 className="mt-2 text-4xl font-bold md:text-6xl">Arrival Flight Assistant</h1><p className="mt-4 text-gray-400">Enter your flight number and Tripelor can look up the scheduled arrival into Malé, then recommend a suitable Dream Speed transfer to V. Felidhoo.</p>
 <div className="card mt-8 p-6"><div className="flex items-center gap-2 text-gold"><Plane/> <b>Your flight</b></div><div className="mt-5 grid gap-3 md:grid-cols-[1.2fr_auto]"><input value={flight} onChange={e=>{setFlight(e.target.value.toUpperCase());setFlightInfo(null);setLookupStatus("")}} placeholder="Flight number (e.g. EK652)" className="rounded-xl border border-white/10 bg-black px-4 py-3"/><button type="button" onClick={lookupFlight} disabled={lookup} className="btn-gold gap-2"><Search className="h-4 w-4"/>{lookup?"Looking up...":"Find My Flight"}</button></div><p className="mt-2 text-xs text-gray-500">Optional: choose the arrival date first if the same flight number operates every day.</p>
 {lookupStatus&&<div className={`mt-4 rounded-xl border p-4 text-sm ${flightInfo?"border-emerald-500/30 bg-emerald-500/10 text-emerald-200":"border-amber-500/30 bg-amber-500/10 text-amber-100"}`}>{lookupStatus}</div>}
 {flightInfo&&<div className="mt-4 rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-[.2em] text-gold">Flight found</p><h2 className="mt-1 text-2xl font-bold">{flightInfo.airline?`${flightInfo.airline} · `:""}{flightInfo.flightNumber}</h2><p className="mt-1 text-sm text-gray-400">{flightInfo.origin||flightInfo.originIata||"Origin"} → {flightInfo.arrivalAirport||"Velana International Airport"}</p></div><CheckCircle2 className="h-6 w-6 text-emerald-400"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 md:grid-cols-4"><div className="rounded-xl bg-black/40 p-3"><p className="text-xs text-gray-500">Arrival date</p><b>{flightInfo.arrivalDate}</b></div><div className="rounded-xl bg-black/40 p-3"><p className="text-xs text-gray-500">Arrival time</p><b>{nice(flightInfo.arrivalTime)}</b></div><div className="rounded-xl bg-black/40 p-3"><p className="text-xs text-gray-500">Terminal</p><b>{flightInfo.terminal||"TBC"}</b></div><div className="rounded-xl bg-black/40 p-3"><p className="text-xs text-gray-500">Status</p><b>{flightInfo.status||"Scheduled"}</b></div></div></div>}
 <div className="mt-5 grid gap-4 md:grid-cols-2"><label className="grid gap-2 text-sm">Arrival date<input required type="date" value={date} onChange={e=>setDate(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3"/></label><label className="grid gap-2 text-sm">Arrival time<input required type="time" value={time} onChange={e=>setTime(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3"/></label></div>
 {date&&time&&<div className={`mt-5 rounded-2xl border p-5 ${rec?"border-emerald-500/30 bg-emerald-500/10":"border-amber-500/30 bg-amber-500/10"}`}>{schedule.length===0?<><b>Schedule confirmation required</b><p className="mt-1 text-sm text-gray-300">Send your details and Tripelor will recommend the best transfer.</p></>:rec?<><p className="text-xs uppercase tracking-[.2em] text-emerald-300">Recommended transfer</p><h2 className="mt-1 text-2xl font-bold"><Ship className="mr-2 inline text-gold"/>Dream Speed · {nice(rec.departure_time)}</h2><p className="mt-2 text-sm text-gray-300">Includes approximately 90 minutes after landing for immigration, baggage and airport exit.</p><p className="mt-3 font-semibold text-gold">{seats} passenger{Number(seats)>1?"s":""} · USD {Number(seats)*PRICE}</p></>:<><div className="flex gap-3"><AlertTriangle className="h-5 w-5 text-amber-400"/><div><b>No comfortable same-day connection found</b><p className="mt-1 text-sm text-gray-300">There is no scheduled departure at least 90 minutes after your arrival. Send the request and Tripelor will help with the best option.</p></div></div></>}</div>}</div>
 <form onSubmit={submit} className="card mt-6 grid gap-5 p-6"><div className="grid gap-4 md:grid-cols-2"><div className="rounded-xl border border-gold/30 bg-gold/10 p-4"><b className="text-gold">USD 50 per person</b><p className="mt-1 text-sm text-gray-300">Pay the boat operator or Uhoo&apos;s Lavish Oasis.</p></div><div className="rounded-xl border border-gold/30 bg-gold/10 p-4"><b className="text-gold">Book at least 24 hours ahead</b><p className="mt-1 text-sm text-gray-300">Transfer schedule and seats are subject to confirmation.</p></div></div><label className="grid gap-2"><span className="flex gap-2"><Users className="text-gold"/>Passengers / seats</span><select value={seats} onChange={e=>setSeats(e.target.value)} className="rounded-xl border border-white/10 bg-black px-4 py-3">{Array.from({length:20},(_,i)=>i+1).map(n=><option key={n}>{n}</option>)}</select></label><div className="grid gap-4 md:grid-cols-3"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Full name" className="rounded-xl border border-white/10 bg-black px-4 py-3"/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className="rounded-xl border border-white/10 bg-black px-4 py-3"/><input required value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone / WhatsApp" className="rounded-xl border border-white/10 bg-black px-4 py-3"/></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Transfer notes" className="rounded-xl border border-white/10 bg-black px-4 py-3"/>{status&&<div className="rounded-xl bg-white/5 p-4 text-sm">{status}</div>}<button disabled={sending} className="btn-gold w-full md:w-auto"><Mail className="h-5 w-5"/>{sending?"Sending...":"Request Recommended Speedboat"}</button><p className="text-xs text-gray-500">Flight times come from an external aviation-data provider and can change. Final speedboat departure and seat availability still require confirmation.</p></form></div></section>}
