"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {LockKeyhole} from "lucide-react";

export default function ResetPasswordPage(){
 const[password,setPassword]=useState("");const[confirm,setConfirm]=useState("");const[accessToken,setAccessToken]=useState("");const[status,setStatus]=useState("");const[busy,setBusy]=useState(false);const[done,setDone]=useState(false);
 useEffect(()=>{const hash=new URLSearchParams(window.location.hash.replace(/^#/,""));const query=new URLSearchParams(window.location.search);setAccessToken(hash.get("access_token")||query.get("access_token")||"");},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setStatus("");if(password.length<8){setStatus("Use at least 8 characters for your new password.");return}if(password!==confirm){setStatus("Passwords do not match.");return}if(!accessToken){setStatus("This reset link is invalid or expired. Please request a new one.");return}setBusy(true);try{const r=await fetch(`${process.env.NEXT_PUBLIC_SUPABASE_URL}/auth/v1/user`,{method:"PUT",headers:{apikey:process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||"",Authorization:`Bearer ${accessToken}`,"Content-Type":"application/json"},body:JSON.stringify({password})});const x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(x?.msg||x?.message||"Unable to update password.");setDone(true);setStatus("Your password has been updated. You can now log in with your new password.");}catch(e){setStatus(e instanceof Error?e.message:"Unable to update password.");}finally{setBusy(false)}}
 return <main className="relative min-h-screen overflow-hidden"><img src="https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=2200&q=90" alt="Maldives" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-black/75"/><div className="container relative flex min-h-screen items-center justify-center py-12"><div className="w-full max-w-md rounded-3xl border border-white/10 bg-black/85 p-7 shadow-2xl backdrop-blur-xl md:p-9"><LockKeyhole className="mx-auto h-8 w-8 text-gold"/><h1 className="mt-4 text-center text-3xl font-bold">Create a new password</h1><p className="mt-3 text-center text-sm text-gray-400">Choose a secure new password for your Tripelor account.</p>{done?<div className="mt-7 grid gap-4"><p className="rounded-xl border border-green-500/30 bg-green-500/10 p-4 text-sm text-green-200">{status}</p><Link href="/login" className="btn-gold">Log In</Link></div>:<form onSubmit={submit} className="mt-7 grid gap-4"><input required type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="New password" autoComplete="new-password" className="rounded-xl border border-white/10 bg-black/70 px-4 py-3"/><input required type="password" minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Confirm new password" autoComplete="new-password" className="rounded-xl border border-white/10 bg-black/70 px-4 py-3"/>{status&&<p className="rounded-xl border border-white/10 bg-white/[.05] p-3 text-sm">{status}</p>}<button disabled={busy} className="btn-gold disabled:opacity-60">{busy?"Updating...":"Update Password"}</button><Link href="/forgot-password" className="text-center text-sm text-gray-400 hover:text-gold">Request a new reset link</Link></form>}</div></div></main>}
