import Image from "next/image";
import Link from "next/link";
import { CheckCircle2, Moon, Utensils, Waves, Fish, Map, Ship } from "lucide-react";

const photos=[
"https://images.unsplash.com/photo-1530789253388-582c481c54b0?q=80&w=1400&auto=format&fit=crop",
"https://images.unsplash.com/photo-1544551763-77ef2d0cfc6c?q=80&w=1400&auto=format&fit=crop",
"https://images.unsplash.com/photo-1504512485720-7d83a16ee930?q=80&w=1400&auto=format&fit=crop",
"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1400&auto=format&fit=crop"
];

export default function Page(){return <main><section className="container py-14"><p className="text-sm uppercase tracking-[0.3em] text-gold">Tripelor Package</p><h1 className="mt-2 text-4xl font-bold md:text-6xl">Maldives Ocean Discovery Escape</h1><p className="mt-4 max-w-3xl text-lg text-gray-400">Five nights with Full Board dining and a richer mix of sea and island experiences — snorkeling, night fishing and island hopping.</p><div className="mt-10 grid gap-3 md:grid-cols-2"><div className="relative h-[480px] overflow-hidden rounded-2xl"><Image src={photos[0]} alt="Maldives Ocean Discovery Escape" fill className="object-cover"/></div><div className="grid grid-cols-2 gap-3">{photos.slice(1).map((p,i)=><div key={p} className={`relative overflow-hidden rounded-2xl ${i===0?"col-span-2 h-[230px]":"h-[235px]"}`}><Image src={p} alt={`Ocean Discovery ${i+2}`} fill className="object-cover"/></div>)}</div></div>
<div className="mt-12 grid gap-8 lg:grid-cols-[1fr_.7fr]"><div><h2 className="text-3xl font-bold">From reef mornings to fishing under the stars</h2><p className="mt-4 leading-8 text-gray-400">This package blends comfort and adventure. Your Full Board meal plan keeps dining simple while your experience days take you out onto the water and into local island life. Swim above tropical reefs, visit another island and spend an evening trying traditional Maldivian night fishing beneath the stars.</p><h3 className="mt-9 text-2xl font-semibold">Package includes</h3><div className="mt-5 grid gap-4 sm:grid-cols-2">{["5-night stay","Full Board meal plan","Snorkeling experience","Night fishing trip","Island hopping experience","Tripelor booking support"].map(x=><div key={x} className="flex gap-3"><CheckCircle2 className="h-5 w-5 shrink-0 text-gold"/><span>{x}</span></div>)}</div><h3 className="mt-9 text-2xl font-semibold">Suggested experience plan</h3><div className="mt-4 space-y-3 text-gray-400"><p><strong className="text-white">Day 1:</strong> Arrival, check-in and Full Board stay begins.</p><p><strong className="text-white">Day 2:</strong> Snorkeling experience and island relaxation.</p><p><strong className="text-white">Day 3:</strong> Island hopping and local discovery.</p><p><strong className="text-white">Day 4:</strong> Free daytime followed by night fishing after sunset.</p><p><strong className="text-white">Day 5:</strong> Relax, swim and enjoy your final full island day.</p><p><strong className="text-white">Day 6:</strong> Departure.</p></div></div><aside className="card h-fit p-7"><Ship className="h-7 w-7 text-gold"/><h2 className="mt-3 text-2xl font-semibold">Ocean Discovery</h2><div className="mt-6 space-y-4 text-gray-300"><div className="flex items-center gap-3"><Moon className="h-5 w-5 text-gold"/>5 nights</div><div className="flex items-center gap-3"><Utensils className="h-5 w-5 text-gold"/>Full Board</div><div className="flex items-center gap-3"><Waves className="h-5 w-5 text-gold"/>Snorkeling</div><div className="flex items-center gap-3"><Fish className="h-5 w-5 text-gold"/>Night fishing</div><div className="flex items-center gap-3"><Map className="h-5 w-5 text-gold"/>Island hopping</div></div><div className="mt-7 border-t border-white/10 pt-6"><p className="text-sm text-gray-500">Package price</p><strong className="text-4xl text-gold">USD 850</strong><Link href="/booking?package=Maldives%20Ocean%20Discovery%20Escape%20-%20USD%20850&mealPlan=Full%20Board" className="btn-gold mt-6 w-full">Book This Package</Link></div></aside></div></section></main>}
